I.u[10329] = {n:"",t:24,d:"",ep:0,g:518,l:1,wd:false,fm:true,w:0,p:1};
I.u[10330] = {n:"Gift: Belugo",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10331] = {n:"Gift: Slugo",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10332] = {n:"Gift: Amlugo",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10333] = {n:"Gift: Ughat",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10334] = {n:"Gift: Oxo Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10335] = {n:"Gift: Oxo Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10336] = {n:"Gift: Oxo Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10337] = {n:"Gift: Oxo Helmet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10338] = {n:"Gift: Noke\'s Daggers",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10339] = {n:"Gift: Noke\'s Necklace",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10340] = {n:"Gift: Noke\'s Cloak",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10341] = {n:"Gift: Noke\'s Mask",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10342] = {n:"Gift: Solaris Mask",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10343] = {n:"Gift: Solaris Shield",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10344] = {n:"Gift: Solaris Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10345] = {n:"Gift: The Esteban",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10346] = {n:"Gift: Slugly Helmet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10347] = {n:"Gift: Slugly Cloak",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10348] = {n:"Gift: Slugly Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10349] = {n:"Gift: Slugly Amulet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10350] = {n:"Gift: Chisp Fingerless Gloves",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10351] = {n:"Gift: Chisp Helmet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10352] = {n:"Gift: Chisp Shield",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10353] = {n:"Gift: Chisp Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10354] = {n:"Gift: Bedazzling Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10355] = {n:"Gift: Bedazzling Double Hakken Axe",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10356] = {n:"Gift: Bedazzling Fist",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10357] = {n:"Gift: Bedazzling Horns",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10358] = {n:"Gift: Slump Necklace",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10359] = {n:"Gift: Poopapink Staff",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10360] = {n:"Gift: Slump Rollers",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10361] = {n:"Gift: Kwakap",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10362] = {n:"",t:69,d:"",ep:0,g:726,l:30,wd:false,fm:true,w:5,u:true,p:1};
I.u[10363] = {n:"",t:29,d:"",ep:0,g:6,l:1,wd:false,fm:false,w:0,m:true,p:1};
I.u[10364] = {n:"",t:24,d:"",ep:0,g:243,l:1,wd:false,fm:true,w:0,p:1};
I.u[10365] = {n:"",t:93,d:"",ep:0,g:96,l:1,wd:false,fm:true,w:10,ut:true,p:1};
I.u[10366] = {n:"",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[10367] = {n:"",t:24,d:"",ep:0,g:772,l:1,wd:false,fm:true,w:0,p:1};
I.u[10368] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10369] = {n:"",t:10,d:"",ep:0,g:3,l:30,wd:false,fm:false,w:5,p:1};
I.u[10370] = {n:"",t:55,d:"",ep:0,g:326,l:1,wd:false,fm:true,w:1,p:1};
I.u[10371] = {n:"",t:49,d:"",ep:0,g:108,l:1,wd:false,fm:true,w:4,p:1};
I.u[10372] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10373] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10374] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10375] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10376] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10377] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10378] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10379] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10380] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10381] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10382] = {n:"Jeweller Scroll",t:13,d:"You gain Experience as a Jeweller by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10383] = {n:"Jewelmagus Scroll",t:13,d:"You gain Experience as a Jewelmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10384] = {n:"Butcher Scroll",t:13,d:"You gain Experience as a Butcher by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10385] = {n:"Handyman Scroll",t:13,d:"You gain Experience as a Handyman by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10386] = {n:"Sword Smithmagus Scroll",t:13,d:"You gain Experience as a Sword Smithmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10387] = {n:"Hammer Smith Scroll",t:13,d:"You gain Experience as a Hammer Smith by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10388] = {n:"Hammer Smithmagus Scroll",t:13,d:"You gain Experience as a Hammer Smithmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10389] = {n:"Shovel Smith Scroll",t:13,d:"You gain Experience as a Shovel Smith by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10390] = {n:"Shovel Smithmagus Scroll",t:13,d:"You gain Experience as a Shovel Smithmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10391] = {n:"Staff Carvmagus Scroll",t:13,d:"You gain Experience as a Staff Carvmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10392] = {n:"Wand Carvmagus Scroll",t:13,d:"You gain Experience as a Wand Carvmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10393] = {n:"Dagger Smithmagus Scroll",t:13,d:"You gain Experience as a Dagger Smithmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10394] = {n:"Bow Carvmagus Scroll",t:13,d:"You gain Experience as a Bow Carvmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10395] = {n:"Axe Smith Scroll",t:13,d:"You gain Experience as an Axe Smith by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10396] = {n:"Axe Smithmagus Scroll",t:13,d:"You gain Experience as an Axe Smithmagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10397] = {n:"Shield Smith Scroll",t:13,d:"You gain Experience as a Shield Smith by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10398] = {n:"Miner Scroll",t:13,d:"You gain Experience as a Miner by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10399] = {n:"Fishmonger Scroll",t:13,d:"You gain Experience as a Fishmonger by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10400] = {n:"Tailor Scroll",t:13,d:"You gain Experience as a Tailor by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10401] = {n:"Costumagus Scroll",t:13,d:"You gain Experience as a Costumagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10402] = {n:"Alchemist Scroll",t:13,d:"You gain Experience as an Alchemist by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10403] = {n:"Farmer Scroll",t:13,d:"You gain Experience as a Farmer by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10404] = {n:"Hunter Scroll",t:13,d:"You gain Experience as a Hunter by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10405] = {n:"Fisherman Scroll",t:13,d:"You gain Experience as a Fisherman by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10406] = {n:"Mysterious Profession Scroll",t:13,d:"You gain Experience as a ??? by using this scroll.\n(Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10407] = {n:"Shoemagus Scroll",t:13,d:"You gain Experience as a Shoemagus by using this scroll. (Double click to use it).",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:1000};
I.u[10408] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10409] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10410] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10411] = {n:"",t:24,d:"",ep:0,g:206,l:1,wd:false,fm:true,w:0,p:1};
I.u[10412] = {n:"",t:32,d:"",ep:0,g:6,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10413] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[10414] = {n:"Koninginnedag Crown",t:16,d:"To celebrate the birthday of an illustrious queen, a feast is held. This crown is usually worn on the day of the feast. Its magic is very powerful, and it can change the colour of the person who wears it to orange.  \nThis will make it easier to hide among people dressed in this colour.",ep:0,g:251,l:1,wd:false,fm:true,w:10,p:1};
I.u[10415] = {n:"",t:24,d:"",ep:0,g:790,l:1,wd:false,fm:true,w:0,p:1};
I.u[10416] = {n:"",t:24,d:"",ep:0,g:95,l:1,wd:false,fm:true,w:0,p:1};
I.u[10417] = {n:"Dungeon Keeper Soul Stone",t:85,d:"This soul stone contains the souls of a group of monsters - including a dungeon keeper - whose only wish is to come back to life to tear your body to pieces. It can only be used in special arenas, located in big cities.",ep:0,g:1,l:1,wd:false,fm:true,w:1,u:true,p:10};
I.u[10418] = {n:"Archmonster Soul Stone",t:85,d:"This soul stone contains the souls of a group of monsters - including at least one archmonster - whose only wish is to come back to life to tear your body to pieces. It can only be used in special arenas, located in big cities.",ep:0,g:1,l:1,wd:false,fm:true,w:1,u:true,p:10};
I.u[10419] = {n:"",t:15,d:"",ep:0,g:771,l:1,wd:false,fm:true,w:0,p:1};
I.u[10420] = {n:"",t:19,d:"",ep:0,g:8,l:1,wd:false,fm:true,w:5,an:17,e:[2,5,1,1,50,10,false,false],p:1};
I.u[10421] = {n:"",t:82,d:"",ep:0,g:1,l:1,wd:false,fm:false,w:10,p:1};
I.u[10422] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10423] = {n:"",t:30,d:"",ep:0,g:1,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10424] = {n:"",t:24,d:"",ep:0,g:791,l:1,wd:false,fm:true,w:0,p:1};
I.u[10425] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10426] = {n:"",t:32,d:"",ep:0,g:22,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10427] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10428] = {n:"",t:24,d:"",ep:0,g:790,l:1,wd:false,fm:true,w:0,p:1};
I.u[10429] = {n:"",t:24,d:"",ep:0,g:65,l:1,wd:false,fm:true,w:0,p:1};
I.u[10430] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10431] = {n:"",t:30,d:"",ep:0,g:1,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10432] = {n:"Bag of stolen Kamas",t:100,d:"You stole this bag of Kamas. I guess you decided its old owner didn\'t need it any more.",ep:0,g:56,l:1,wd:false,fm:true,w:10,u:true,p:3000};
I.u[10433] = {n:"",t:24,d:"",ep:0,g:49,l:1,wd:false,fm:true,w:0,p:1};
I.u[10434] = {n:"",t:12,d:"",ep:0,g:188,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10435] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10437] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10438] = {n:"",t:11,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:1,p:1};
I.u[10439] = {n:"",t:24,d:"",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:1};
I.u[10440] = {n:"",t:32,d:"",ep:0,g:13,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10441] = {n:"",t:24,d:"",ep:0,g:804,l:1,wd:false,fm:true,w:0,p:1};
I.u[10442] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10443] = {n:"",t:60,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:2,p:100};
I.u[10444] = {n:"",t:24,d:"",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[10445] = {n:"",t:24,d:"",ep:0,g:805,l:1,wd:false,fm:true,w:0,p:1};
I.u[10446] = {n:"",t:24,d:"",ep:0,g:806,l:1,wd:false,fm:true,w:0,p:1};
I.u[10447] = {n:"",t:24,d:"",ep:0,g:500,l:1,wd:false,fm:true,w:0,p:1};
I.u[10448] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10449] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10450] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10451] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10456] = {n:"Sponge Mob Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10164,30",u:true,p:0};
I.u[10457] = {n:"Royal Gobball Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<2083,10",u:true,p:0};
I.u[10458] = {n:"Famished Sunflower Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9774,30",u:true,p:0};
I.u[10459] = {n:"Royal Blue Jelly Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<6831,30",u:true,p:0};
I.u[10460] = {n:"Shin Larva Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8203,30",u:true,p:0};
I.u[10461] = {n:"GM Wabbit Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<1776,30",u:true,p:0};
I.u[10462] = {n:"Golden Scarabugly Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9784,30",u:true,p:0};
I.u[10463] = {n:"Bworkette Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9760,30",u:true,p:0};
I.u[10464] = {n:"Dragon Pig Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8549,16",u:true,p:0};
I.u[10465] = {n:"Mumminotor Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9880,30",u:true,p:0};
I.u[10466] = {n:"Deminoball Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9879,30",u:true,p:0};
I.u[10467] = {n:"Royal Mint Jelly Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<6832,30",u:true,p:0};
I.u[10468] = {n:"Royal Tofu Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9535,30",u:true,p:0};
I.u[10469] = {n:"Royal Coco Blop Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11887,30",u:true,p:0};
I.u[10470] = {n:"Royal Cherry Blop Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11888,30",u:true,p:0};
I.u[10471] = {n:"Royal Indigo Blop Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11890,30",u:true,p:0};
I.u[10472] = {n:"Royal Pippin Blop Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11889,30",u:true,p:0};
I.u[10473] = {n:"Black Rat Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10198,30",u:true,p:0};
I.u[10474] = {n:"White Rat Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10212,30",u:true,p:0};
I.u[10475] = {n:"Minotoror Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9879,30",u:true,p:0};
I.u[10476] = {n:"Dark Vlad Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<325,30",u:true,p:0};
I.u[10477] = {n:"Tanukouï San Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8314,30",u:true,p:0};
I.u[10478] = {n:"Legendary Crackler Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9579,30",u:true,p:0};
I.u[10479] = {n:"Royal Strawberry Jelly Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<6833,30",u:true,p:0};
I.u[10480] = {n:"Lord Crow Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9591,30",u:true,p:0};
I.u[10481] = {n:"Royal Rainbow Blop Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11892,30",u:true,p:0};
I.u[10482] = {n:"Great Coralator Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11079,30",u:true,p:0};
I.u[10483] = {n:"Gourlo the Terrible Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11069,30",u:true,p:0};
I.u[10484] = {n:"Moowolf Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9648,30",u:true,p:0};
I.u[10485] = {n:"Wa Wabbit Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<1774,30",u:true,p:0};
I.u[10486] = {n:"Moon Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<1836,30",u:true,p:0};
I.u[10487] = {n:"Koolich Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8965,30",u:true,p:0};
I.u[10488] = {n:"Skeunk Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8977,30",u:true,p:0};
I.u[10489] = {n:"Ancestral Treechnid Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10234,30",u:true,p:0};
I.u[10490] = {n:"Master Pandora Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8497,30",u:true,p:0};
I.u[10491] = {n:"Tynril Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10812,30",u:true,p:0};
I.u[10492] = {n:"Dismayed Tynril Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10812,30",u:true,p:0};
I.u[10493] = {n:"Disconcerted Tynril Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10812,30",u:true,p:0};
I.u[10494] = {n:"Perfidious Tynril Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10812,30",u:true,p:0};
I.u[10495] = {n:"Royal Lemon Jelly Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<6834,30",u:true,p:0};
I.u[10496] = {n:"Bworker Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<7526,30",u:true,p:0};
I.u[10497] = {n:"Sphincter Cell Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10149,30",u:true,p:0};
I.u[10498] = {n:"Minotot Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9879,30",u:true,p:0};
I.u[10499] = {n:"Silf the Greater Bherb Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11267,30",u:true,p:0};
I.u[10500] = {n:"Crocabulia Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<10109,16",u:true,p:0};
I.u[10501] = {n:"Peki Peki Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<8349,16",u:true,p:0};
I.u[10502] = {n:"Soft Oak Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<9126,30",u:true,p:0};
I.u[10503] = {n:"Ougaa Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11941,30",u:true,p:0};
I.u[10504] = {n:"Kimbo Potion",t:12,d:"This potion will take you straight to the indicated monster.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11133,30",u:true,p:0};
I.u[10506] = {n:"Class Spell Scroll: Dispersing Arrow",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Cras the class spell \'Dispersing Arrow\'.",ep:0,g:7,l:1,wd:true,fm:true,w:1,c:"PG=9",u:true,p:10000};
I.u[10507] = {n:"Class Spell Scroll: Pull Out",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Enutrofs the class spell \'Pull Out\'.",ep:0,g:9,l:1,wd:true,fm:true,w:1,c:"PG=3",u:true,p:10000};
I.u[10508] = {n:"Class Spell Scroll: Reinforced Protection",t:75,d:"(Double click to learn the spell)\nThis scroll will teach Fecas the class spell \'Reinforced Protection\'.",ep:0,g:11,l:1,wd:true,fm:true,w:1,c:"PG=1",u:true,p:10000};
I.u[10509] = {n:"Class Spell Scroll: Mot Olov",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Eniripsas the class spell \'Mot Olov\'.",ep:0,g:10,l:1,wd:true,fm:true,w:1,c:"PG=7",u:true,p:10000};
I.u[10510] = {n:"Class Spell Scroll: Drunkenness",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Pandawas the class spell \'Drunkenness\'.",ep:0,g:12,l:1,wd:true,fm:true,w:1,c:"PG=12",u:true,p:10000};
I.u[10511] = {n:"Class Spell Scroll: Pain Shared",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Sacriers the class spell \'Pain Shared\'.",ep:0,g:8,l:1,wd:true,fm:true,w:1,c:"PG=11",u:true,p:10000};
I.u[10512] = {n:"Class Spell Scroll: The Tree of Life",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Sadidas the class spell \'The Tree of Life\'.",ep:0,g:13,l:1,wd:true,fm:true,w:1,c:"PG=10",u:true,p:10000};
I.u[10513] = {n:"Class Spell Scroll: Rhol Bak",t:75,d:"(Double click to learn the spell) \nThis scroll will teach Xelors the class spell \'Rhol Bak\'.",ep:0,g:15,l:1,wd:true,fm:true,w:1,c:"PG=5",u:true,p:10000};
I.u[10515] = {n:"Gift: Koninginnedag Crown",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10516] = {n:"Spark Transformation",t:27,d:"This is what happens when you play with fire. Maybe it\'s not all bad, though. Go see Magus Ax for advice.",ep:0,g:3,l:1,wd:true,fm:true,w:0,m:true,p:1};
I.u[10517] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10518] = {n:"Recipe for Climbing Rope",t:24,d:"A handyman can make Climbing Rope using the following resources: 30 Hemp, 5 Silk String and 1 Resistant String.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10519] = {n:"Recipe for Impure Corruptah Stone",t:24,d:"An alchemist can make Corruptah Stones of different colours using the following ingredients: \nBlue: 2 Bluish Jellies, 1 Ghetto Raid Potion. \nYellow: 2 Lemon Jellies, 1 Ghetto Raid Potion. \nGreen: 2 Mint Jellies, 1 Ghetto Raid Potion.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10520] = {n:"Recipe for Corruptah Stone",t:24,d:"A miner can make Corruptah Stones of different colours using the following ingredients: \nBlue: 10 Impure Blue Corruptah Stones, 10 Water. \nYellow: 10 Impure Yellow Corruptah Stones, 10 Water. \nGreen: 10 Impure Green Corruptah Stones, 10 Water.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10521] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10522] = {n:"Bombu Barrel recipe",t:24,d:"A handyman can make this barrel from 4 Bombu Planks and 3 Ebonite.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10523] = {n:"Frost Potion recipe",t:24,d:"Frost Potion can be prepared by an alchemist from 1 Frozen Crystal, 1 Element Flask and 1 Blue Triam Metaria.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10524] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10525] = {n:"",t:24,d:"",ep:0,g:41,l:1,wd:false,fm:true,w:0,p:1};
I.u[10526] = {n:"",t:24,d:"",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:1};
I.u[10527] = {n:"",t:24,d:"",ep:0,g:95,l:1,wd:false,fm:true,w:0,p:1};
I.u[10528] = {n:"",t:24,d:"",ep:0,g:790,l:1,wd:false,fm:true,w:0,p:1};
I.u[10529] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10530] = {n:"",t:35,d:"",ep:0,g:141,l:60,wd:false,fm:true,w:1,p:1};
I.u[10531] = {n:"",t:24,d:"",ep:0,g:37,l:1,wd:false,fm:true,w:0,p:1};
I.u[10532] = {n:"",t:51,d:"",ep:0,g:44,l:60,wd:false,fm:true,w:5,p:1};
I.u[10533] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10534] = {n:"",t:12,d:"",ep:0,g:189,l:60,wd:false,fm:true,w:1,p:1};
I.u[10535] = {n:"",t:50,d:"",ep:0,g:7,l:60,wd:false,fm:true,w:10,p:1};
I.u[10536] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10537] = {n:"",t:24,d:"",ep:0,g:808,l:1,wd:false,fm:true,w:0,p:1};
I.u[10538] = {n:"",t:24,d:"",ep:0,g:763,l:1,wd:false,fm:true,w:0,p:1};
I.u[10539] = {n:"",t:32,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10540] = {n:"",t:24,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,p:1};
I.u[10541] = {n:"",t:24,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,p:1};
I.u[10542] = {n:"",t:24,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,p:1};
I.u[10543] = {n:"",t:24,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,p:1};
I.u[10544] = {n:"Jellufo",t:18,d:"This creature from elsewhere was tamed by its former master to only eat blop monsters. This may explain its strange appearance and its Blop\'s breath.",ep:0,g:55,l:1,wd:true,fm:true,w:10,p:1};
I.u[10552] = {n:"Ughat",t:16,d:"This headwear will keep your ears protected from cold and bad jokes.",ep:0,g:245,l:41,wd:true,fm:true,w:10,s:134,p:4525};
I.u[10553] = {n:"Toot\'s Helmet",t:16,d:"Only a Gobbowl player would come up with the crazy idea of disguising themselves as a Tofu to intimidate their opponent. Mind you, this helmet\'s aerodynamic shape allows the wearer to slice through the air like a missile. Maybe it\'s not such a crazy idea after all. Well, whatever, you\'ll certainly stand out from the crowd.",ep:0,g:252,l:41,wd:false,fm:true,w:10,s:142,p:4550};
I.u[10554] = {n:"Benji\'s Helmet",t:16,d:"It\'s the integrated red sunglasses that make this the helmet of choice for any self-respecting Lamechester United player.",ep:0,g:253,l:41,wd:false,fm:true,w:10,s:143,p:4550};
I.u[10555] = {n:"Real Gobbly Shield",t:82,d:"This imposing shield bears the marks of many a Gobbowl match. However, despite its robust, intimidating appearance, it\'d be of no use at all in a real fight. You\'d be better off using it to play peek-a-boo with Gobblies.",ep:0,g:54,l:1,wd:false,fm:true,w:10,c:"PP>0",s:142,p:1};
I.u[10556] = {n:"Lamechester United Shield",t:82,d:"This imposing shield perfectly sums up today\'s youth: style over substance - all bark, and no bite. It\'d be good for nothing in a real fight, unless your opponent was coming at you with a ball.",ep:0,g:53,l:1,wd:false,fm:true,w:10,c:"PP>0",s:143,p:1};
I.u[10557] = {n:"Real Gobbly Glove",t:9,d:"This battered old glove helps you catch Gobbowl balls, or any other round thing covered in wool, for that matter. What you do with it as result concerns you, and you only...",ep:0,g:176,l:43,wd:true,fm:true,w:10,s:142,p:4500};
I.u[10558] = {n:"Lamechester United Glove",t:9,d:"With this glove on your hand, you can pretend you\'re a famous Gobbowl player when you\'re playing fetch with your BowWow.",ep:0,g:177,l:43,wd:true,fm:true,w:10,s:143,p:4500};
I.u[10559] = {n:"Toot\'s Belt",t:10,d:"Gobbowl matches are brutal, and this belt was designed to protect players from muscular blows. However, you can also use it as a life-belt when you\'re taking a bath. Who\'d have thought?",ep:0,g:159,l:41,wd:false,fm:true,w:10,s:142,p:4600};
I.u[10560] = {n:"Monty\'s Belt",t:10,d:"They say that Gobbowl is a game for real men. This belt\'s for real men too, with plenty of protective padding to soften low blows. It\'s also great for training young Srams.",ep:0,g:160,l:41,wd:false,fm:true,w:10,s:143,p:4600};
I.u[10561] = {n:"Real Gobbly Boots",t:11,d:"These boots have been around for a while, you can certainly smell that. Plant them on your feet and you\'ll look just like a real Gobbowl player. Plant their crampons in the rump of a few Gobblies, and the fans will come flocking.",ep:0,g:144,l:42,wd:false,fm:true,w:10,s:142,p:4825};
I.u[10562] = {n:"Lamechester United Boots",t:11,d:"\"Fashionable footwear feeds fascinated fan\'s frenzy\", reads the latest headline, and for once, the papers aren\'t wrong. When properly polished, these boots help make it look like your opponent pushed you over, when in fact, you slipped. Congratulations! You\'ve just learnt one of the basics of Gobbowl.",ep:0,g:145,l:42,wd:false,fm:true,w:10,s:143,p:4825};
I.u[10563] = {n:"Magical Orb",t:50,d:"This orb allows you to redistribute your characteristic points. Temple masters know how to use it.",ep:0,g:460,l:1,wd:true,fm:true,w:100,p:1000};
I.u[10564] = {n:"Magical Orb Box",t:89,d:"This box contains a carefully wrapped orb.",ep:0,g:42,l:1,wd:true,fm:true,w:0,u:true,p:1};
I.u[10565] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10566] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10567] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10568] = {n:"",t:24,d:"",ep:0,g:65,l:1,wd:false,fm:true,w:0,p:1};
I.u[10569] = {n:"",t:15,d:"",ep:0,g:773,l:50,wd:false,fm:true,w:1,p:1};
I.u[10570] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10571] = {n:"",t:15,d:"",ep:0,g:774,l:50,wd:false,fm:true,w:1,p:1};
I.u[10572] = {n:"",t:24,d:"",ep:0,g:41,l:1,wd:false,fm:true,w:0,p:1};
I.u[10573] = {n:"",t:52,d:"",ep:0,g:254,l:60,wd:false,fm:true,w:1,p:1};
I.u[10574] = {n:"",t:24,d:"",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10575] = {n:"",t:5,d:"",ep:0,g:16,l:100,wd:false,fm:false,w:10,an:13,e:[15,3,1,1,50,15,false,false],p:1};
I.u[10576] = {n:"",t:24,d:"",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:1};
I.u[10577] = {n:"",t:15,d:"",ep:0,g:242,l:80,wd:false,fm:true,w:1,p:100};
I.u[10578] = {n:"",t:24,d:"",ep:0,g:736,l:1,wd:false,fm:true,w:0,p:1};
I.u[10579] = {n:"",t:9,d:"",ep:0,g:3,l:100,wd:false,fm:false,w:1,p:10};
I.u[10580] = {n:"",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10581] = {n:"",t:24,d:"",ep:0,g:41,l:1,wd:false,fm:true,w:0,p:1};
I.u[10582] = {n:"",t:32,d:"",ep:0,g:3,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10584] = {n:"",t:24,d:"",ep:0,g:809,l:1,wd:false,fm:true,w:0,p:1};
I.u[10585] = {n:"",t:24,d:"",ep:0,g:500,l:1,wd:false,fm:true,w:0,p:1};
I.u[10586] = {n:"",t:24,d:"",ep:0,g:41,l:1,wd:false,fm:true,w:0,p:1};
I.u[10587] = {n:"",t:55,d:"",ep:0,g:430,l:100,wd:false,fm:true,w:1,p:1};
I.u[10588] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10589] = {n:"",t:12,d:"",ep:0,g:141,l:60,wd:false,fm:true,w:1,p:1};
I.u[10590] = {n:"",t:24,d:"",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:1};
I.u[10591] = {n:"",t:48,d:"",ep:0,g:261,l:60,wd:false,fm:true,w:1,p:1};
I.u[10592] = {n:"",t:24,d:"",ep:0,g:55,l:1,wd:false,fm:true,w:0,p:1};
I.u[10593] = {n:"",t:15,d:"",ep:0,g:775,l:80,wd:false,fm:true,w:1,p:100};
I.u[10594] = {n:"",t:24,d:"",ep:0,g:810,l:1,wd:false,fm:true,w:0,p:1};
I.u[10595] = {n:"",t:9,d:"",ep:0,g:5,l:100,wd:false,fm:false,w:1,p:10};
I.u[10596] = {n:"",t:50,d:"",ep:0,g:22,l:100,wd:false,fm:true,w:1,p:1};
I.u[10597] = {n:"Jellufo Ghost",t:90,d:"This Jellufo hasn\'t left the living world yet. Will you find a way to resurrect it or cowardly abandon it once and for all?",ep:0,g:55,l:1,wd:true,fm:true,w:1,p:1};
I.u[10598] = {n:"Gift: Jellufo",t:89,d:"If you shake this object vigorously and hold your ear to it, you\'ll hear a strange noise... like a tiny animal weeping... yeah, actually maybe you don\'t want to shake it... Ahhh, just open the damn thing. You\'ll find a wonderful pet inside it, as well as some food and healing Eniripsa powders.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10599] = {n:"Bow Kennel Certificate: Jellufo",t:77,d:"This certificate describes the characteristics of the Jellufo you\'ve put in the Bow Kennel.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10600] = {n:"",t:24,d:"",ep:0,g:766,l:1,wd:false,fm:true,w:0,p:1};
I.u[10601] = {n:"Certificate of Restoration",t:24,d:"This document certifies that your characteristics have been reset to zero.",ep:0,g:33,l:1,wd:true,fm:true,w:0,p:0};
I.u[10602] = {n:"Spell Scroll: Mount Taming",t:75,d:"This scroll will teach you the special spell \'Mount Taming\'.",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10603] = {n:"Spell Scroll: Soul Capture",t:75,d:"This scroll will teach you the special spell \'Soul Capture\'.",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10604] = {n:"Spell Scroll: Moon Hammer",t:75,d:"This scroll will teach you the elementary spell \'Moon Hammer\'.",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10605] = {n:"Spell Scroll: Perfidious Boomerang",t:75,d:"This scroll will teach you the elementary spell \'Perfidious Boomerang\'.",ep:0,g:3,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10606] = {n:"White Rat Spiritual Gem",t:85,d:"This gem is awarded after a certain number of victories in duels, and it contains the soul of a monster. Keep in a cool, dry, dark place, away from strong odours. Shake well before use.",ep:0,g:2,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10607] = {n:"",t:24,d:"",ep:0,g:766,l:1,wd:false,fm:true,w:0,p:1};
I.u[10608] = {n:"Potion Vers Kralamoure Géant",t:12,d:"Cette potion vous mènera directement vers le monstre indiqué.",ep:0,g:17,l:1,wd:false,fm:true,w:1,c:"MK<11095,30",u:true,p:0};
I.u[10609] = {n:"",t:1,d:"",ep:0,g:0,l:33,wd:false,fm:true,w:10,p:5};
I.u[10610] = {n:"",t:1,d:"",ep:0,g:0,l:33,wd:false,fm:true,w:10,p:5};
I.u[10611] = {n:"",t:1,d:"",ep:0,g:0,l:34,wd:false,fm:true,w:10,p:3325};
I.u[10612] = {n:"",t:1,d:"",ep:0,g:0,l:33,wd:false,fm:true,w:10,p:3075};
I.u[10613] = {n:"Pa Pi Rune",t:78,d:"This rune increases its traps powers.",ep:0,g:23,l:20,wd:true,fm:true,w:1,p:10};
I.u[10615] = {n:"Pa Pi Per Rune",t:78,d:"This rune increases its traps powers.",ep:0,g:24,l:20,wd:true,fm:true,w:1,p:10};
I.u[10616] = {n:"Ra Pi Per Rune",t:78,d:"This rune increases its traps powers.",ep:0,g:24,l:30,wd:true,fm:true,w:1,p:10};
I.u[10618] = {n:"Pa Do Per Rune",t:78,d:"This rune increases the damage dealt to opponents.",ep:0,g:16,l:30,wd:true,fm:true,w:1,p:10};
I.u[10619] = {n:"Ra Do Per Rune",t:78,d:"This rune increases the damage dealt to its opponents.",ep:0,g:16,l:30,wd:true,fm:true,w:1,p:10};
I.u[10621] = {n:"The Sacre\'s Orders",t:24,d:"This torn piece of paper lists all the instructions of the Sacre Family. They are quite simple. They order you to track and execute a target. And do not come back before 10 minutes after the fight.",ep:0,g:176,l:1,wd:true,fm:true,w:0,p:0};
I.u[10622] = {n:"Grute\'s Sword",t:6,d:"This sword allowed Grute the Bwork to cut his opponents\' nuts in two, which is usually enough to make anyone give up a fight. This magical weapon is still imbued with the personality of Grute. If you equip it, you may well become him.",ep:0,g:94,l:41,wd:true,fm:false,w:10,an:0,e:[5,5,1,1,50,50,false,false],s:144,p:4600};
I.u[10623] = {n:"Grute\'s Amulet",t:1,d:"Grute the Bwork wasn\'t very smart. In fact, he was as thick as two short planks. Fortunately, traditional teaching methods work equally well on Bworks than on children. After a few well-deserved strokes of the cane over the years, Grute became a real little brute.",ep:0,g:153,l:42,wd:true,fm:true,w:10,s:144,p:4900};
I.u[10624] = {n:"Grute\'s Belt",t:10,d:"Those who have had to face Grute the Bwork will tell you, \"Don\'t bother aiming for the head, it\'s empty\". This advice also applies to all those who face Iops, Goblins or mothers-in-law.",ep:0,g:163,l:40,wd:true,fm:true,w:10,s:144,p:4300};
I.u[10625] = {n:"Grute\'s Boots",t:11,d:"Grute\'s Boots give off such a pungent aroma that you\'ll be able to knock your opponents out with one quick kick to their head. These boots were forbidden in combat situations by the Sufokia Convention a long time ago, a convention which, it has to be said, has saved many, many lives.",ep:0,g:150,l:44,wd:true,fm:true,w:10,s:144,p:5250};
I.u[10626] = {n:"Koksiks\' Sword",t:6,d:"The life of a Chafer Foot Soldier is not as rosy as you\'d think. Although I\'m not sure you\'ve ever thought about it. Iop knows I\'ve never thought of it myself, the life of a good, long, tall, strong Chafer Foot Soldier like Koksiks. In fact, I often lie awake at night, not thinking of the life of a Chafer Foot Soldier. Wonderful lads.\nAnyway, enough of that. This sword is still infused with the spirit of Koksiks, and by equipping it, you could become him.",ep:0,g:95,l:41,wd:true,fm:false,w:10,an:0,e:[5,5,1,1,50,50,false,false],s:145,p:4600};
I.u[10627] = {n:"Koksiks\' Ring",t:9,d:"This ring belonged to Koksiks himself, and a lovely ring it is too. He let me have it once... but took it back some months later. Ahh. When I think of it now...",ep:0,g:179,l:41,wd:true,fm:true,w:10,s:145,p:4650};
I.u[10628] = {n:"Koksiks\' Boots",t:11,d:"You should have seen Koksiks go in these boots. A sight to behold he was. Dancing. We danced once, but that was... a long time ago.",ep:0,g:149,l:42,wd:true,fm:true,w:10,s:145,p:4800};
I.u[10629] = {n:"Koksiks\' Belt",t:10,d:"Chafer Koksiks the infantryman had two dreams in life: to climb Crackler mountain and to become a full-time minstrel. Life was very cruel to him - he ended up playing support for Jon Lemon... who made his name, and his entire career, playing unpaid charity gigs.",ep:0,g:164,l:42,wd:true,fm:true,w:10,s:145,p:4900};
I.u[10630] = {n:"Goboff\'s Staff",t:4,d:"This staff looks very much like a lance... in fact, Goboff the Goblin used it to cut the tops off his boiled Giant Tofu eggs, back when the birds existed. What he used for toast soldiers is anyone\'s guess. \nThis magic weapon is still imbued with the spirit of Goboff. If you equip it, you could perhaps become him.",ep:0,g:90,l:43,wd:true,fm:false,w:10,an:0,e:[10,5,1,1,50,50,false,false],s:146,p:5040};
I.u[10631] = {n:"Goboff\'s Amulet",t:1,d:"A popular saying amongst Goblins is \"Sometimes you get the bear, sometimes the bear gets you\". If you look at Goblins closely, this saying is better summarised as \"Sometimes the bear gets you\".",ep:0,g:152,l:42,wd:true,fm:true,w:10,s:146,p:4837};
I.u[10632] = {n:"Goboff\'s Belt",t:10,d:"Goboff the Goblin loved to gobble rotten eggs. His digestive tract might have been able to deal with this atrocious habit, but those unlucky enough to get a whiff of his foul breath weren\'t, and fell like Moskitoes. Those unlucky enough not to be rendered unconscious immediately would grab onto this belt to stop themselves hitting the floor.",ep:0,g:165,l:42,wd:true,fm:true,w:10,s:146,p:4800};
I.u[10633] = {n:"Goboff\'s Ring",t:9,d:"Goboff the Goblin was a keen gardener. He loved nothing more than whacking trespassers around the head with his rake. He found this ring on the finger of an impudent rambler who\'d dared to trample his Salad leaves.",ep:0,g:180,l:44,wd:true,fm:true,w:10,s:146,p:5250};
I.u[10634] = {n:"Lektor\'s Bow",t:2,d:"Kanniball Lektor used this weapon to hunt his prey, and send a few arrows his children\'s\' way when he was in a playful mood. This magic weapon is still imbued with the spirit of Kanniball Lektor. If you equip it, you could perhaps become him.",ep:0,g:68,l:41,wd:true,fm:false,w:10,an:0,tw:true,e:[10,5,1,5,30,50,false,false],s:147,p:2000};
I.u[10635] = {n:"Lektor\'s Amulet",t:1,d:"When the two small balls attached to this amulet collide, they produce a slight rattling noise, which means a Kanniball is very close by. When you hear this noise, it is usually too late to escape, but there is still time to choose which sauce you want to be devoured with.",ep:0,g:151,l:41,wd:true,fm:true,w:10,s:147,p:4525};
I.u[10636] = {n:"Lektor\'s Ring",t:9,d:"The ring is infused with secret spices, used for flavouring broth when stirred by hand. The spices are so good that once you put the ring on, there\'s a real risk you\'ll bite your own fingers off, they\'ll be that tasty.",ep:0,g:178,l:42,wd:true,fm:true,w:10,s:147,p:4837};
I.u[10637] = {n:"Lektor\'s Boots",t:11,d:"Kanniball Lektor wore these boots for several years before trading them in for a tourist on Moon Island. Look, he was hungry, alright?",ep:0,g:148,l:43,wd:true,fm:true,w:10,s:147,p:5050};
I.u[10638] = {n:"Stroy Zemol\'s Sword",t:6,d:"Pandit Stroy Zemol used to hit his adversaries with the flat of this weapon\'s blade in order to knock them out without causing a scratch. Cursed for years with taunts about his name, the Pandit did not want to destroy them all, just render them unconscious for a while. This weapon is still infused with the spirit of Stroy Zemol, and by equipping it, you could become him.",ep:0,g:93,l:41,wd:true,fm:false,w:10,an:0,e:[3,5,1,1,30,50,false,false],s:148,p:4600};
I.u[10639] = {n:"Stroy Zemol\'s Amulet",t:1,d:"Stroy Zemol had a sister, Faye Pworme. She liked travelling alone and exploring dark, foul-smelling tunnels.",ep:0,g:154,l:41,wd:true,fm:true,w:10,s:148,p:4525};
I.u[10640] = {n:"Stroy Zemol\'s Belt",t:10,d:"This belt is allegedly reversible, only no one\'s ever dared try it as they don\'t want to be the first to discover that it isn\'t actually reversible.",ep:0,g:161,l:40,wd:true,fm:true,w:10,s:148,p:4475};
I.u[10641] = {n:"Stroy Zemol\'s Boots",t:11,d:"Stroy Zemol made these boots himself, from a few blocks of wood and a little bit of fabric. They might not look like other boots, but blimey, they\'re certainly magical nevertheless.",ep:0,g:147,l:41,wd:true,fm:true,w:10,s:148,p:4550};
I.u[10642] = {n:"Fyred Ampe\'s Pickaxe",t:21,d:"Fyred Ampe the Dark Miner used this pickaxe to carve out the famous bottomless Kruup mine, in which Gaddie lived for several years. This weapon is still impregnated with the spirit of Fyred Ampe. By equipping it, you could become him.",ep:0,g:2,l:41,wd:true,fm:false,w:10,an:0,e:[5,5,1,1,50,50,false,false],s:149,p:4600};
I.u[10643] = {n:"Fyred Ampe\'s Ring",t:9,d:"When it comes into contact with warm, sticky liquids, this ring changes colour, which explains why Fyred Ampe the Dark Miner loved it so much.",ep:0,g:181,l:43,wd:true,fm:true,w:10,s:149,p:5107};
I.u[10644] = {n:"Fyred Ampe\'s Boots",t:11,d:"The soles of these magic boots allow you to shatter lumps of coal by vibrating at its resonant frequency (look it up). The user guide indicates that they will even vibrate on their own when Slamdance music is played nearby.",ep:0,g:146,l:41,wd:true,fm:true,w:10,s:149,p:4575};
I.u[10645] = {n:"Fyred Ampe\'s Belt",t:10,d:"This belt, reinforced with several different metals, was strong enough to support the weight of Fyred Ampe the Dark Miner\'s enormous sack. Don\'t worry, though, it should be just as useful for tiny packets too.",ep:0,g:162,l:43,wd:true,fm:true,w:10,s:149,p:5050};
I.u[10646] = {n:"Swashbuckling Bandit Amulet",t:1,d:"Boo",ep:0,g:76,l:30,wd:false,fm:true,w:1,p:1};
I.u[10647] = {n:"Gift: Real Gobbly Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10648] = {n:"Gift: Toot\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10649] = {n:"Gift: Real Gobbly Glove",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10650] = {n:"Gift: Real Gobbly Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10651] = {n:"Gift: Toot\'s Helmet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10652] = {n:"Gift: Lamechester United Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10653] = {n:"Gift: Monty\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10654] = {n:"Gift: Lamechester United Glove",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10655] = {n:"Gift: Lamechester United Shield",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10656] = {n:"Gift: Benji\'s Helmet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:true,fm:true,w:1,u:true,p:1};
I.u[10657] = {n:"Ogrine Seeker",t:18,d:"This strange pet is the result of cross-breeding Amakna\'s greatest truffle hunters. Its enormous snout allows it to locate Ogrine, even if it is hidden underwater. It took Otomai several years to create this beast. It is said he used it to find something he thought he\'d lost, something that had escaped from him. In doing so, he fixed one of his many mistakes. \nNo one knows for sure. What is certain is the process of hunting Ogrine is so complicated and uses so much energy, that this creature is obliged to eat monster souls to develop. It was raised on the beaches of Otomai\'s Island and will only eat the souls of the creatures that live there.",ep:0,g:56,l:1,wd:true,fm:true,w:10,p:1};
I.u[10658] = {n:"Ogrine Seeker Ghost",t:90,d:"This Ogrine Seeker Ghost hasn\'t left the living world yet. Will you find a way to resurrect it or cowardly abandon it once and for all?",ep:0,g:56,l:1,wd:true,fm:true,w:1,p:1};
I.u[10659] = {n:"Ogrine Seeker Egg",t:72,d:"This strange egg contains a tiny magical creature. Keep it warm, and it\'s sure to hatch.",ep:0,g:206,l:1,wd:false,fm:true,w:0,u:true,p:1};
I.u[10660] = {n:"Gift: Ogrine Seeker Egg",t:89,d:"If you shake this object vigorously and hold your ear to it, you\'ll hear a strange noise... like a tiny animal weeping... yeah, actually maybe you don\'t want to shake it... Ahhh, just open the damn thing. You\'ll find a wonderful pet inside it, as well as some food and healing Eniripsa powders.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10661] = {n:"Bow Kennel Certificate: Ogrine Seeker",t:77,d:"This certificate describes the characteristics of the Ogrine Seeker you\'ve put in the Bow Kennel.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10662] = {n:"Pa Prospe Rune",t:78,d:"This Rune will increase your luck in finding rare items.",ep:0,g:36,l:20,wd:true,fm:true,w:1,p:10};
I.u[10663] = {n:"Gobball-meat Pasty",t:33,d:"You\'ll need a strong stomach to swallow this pasty. The gobball meat used in it, not always the freshest cut it has to be said, gives it a flavour akin to oysters in chocolate. Bworks go mad for it.",ep:0,g:71,l:20,wd:true,fm:true,w:1,c:"Sc=1",u:true,ut:true,p:1};
I.u[10664] = {n:"Treechorn",t:94,d:"If you rub this tiny acorn gently, it will begin to swell, and after a short time, if you rub a little more, the treechnid trapped inside it will come bursting out.",ep:0,g:15,l:1,wd:true,fm:true,w:0,c:"Sc=2&(PB=4|PB=22|PB=33|PB=169|PB=170|PB=486|PB=168)",u:true,p:0};
I.u[10665] = {n:"Jorbak\'s Chest",t:94,d:"Jorbak lost his entire fortune, could it be hidden inside this strange trunk? Open it and find out.",ep:0,g:16,l:1,wd:true,fm:true,w:1,u:true,p:0};
I.u[10667] = {n:"Jorbak\'s Imprint",t:24,d:"You\'ve noted down when Jorbak\'s spirit will be visible. No need to rush things.",ep:0,g:251,l:1,wd:true,fm:true,w:0,p:0};
I.u[10668] = {n:"Jorbak\'s Good Fortune",t:28,d:"For a short time, you\'ll benefit from Jorbak\'s luck.",ep:0,g:16,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10669] = {n:"Prancing Chimera Potion",t:12,d:"That\'ll teach you to drink whatever is put in front of you!",ep:0,g:18,l:1,wd:true,fm:true,w:1,c:"Sc=4",u:true,p:0};
I.u[10670] = {n:"Percimol\'s Scroll",t:94,d:"As easy to follow as a Wabbit\'s Wecipe, this scroll\'s instructions reveal a bewitching secret.",ep:0,g:17,l:1,wd:true,fm:true,w:1,c:"Sc=5",u:true,p:0};
I.u[10673] = {n:"HmmMmmMmmm Potion",t:12,d:"HmmMmmMmmm.",ep:0,g:191,l:1,wd:true,fm:false,w:1,c:"Sc=7",u:true,ut:true,p:1};
I.u[10674] = {n:"Mmmmm",t:28,d:"Mmmmm mm mmmmmm mmmmm, mmm mmm mm mmmmmm mmmmm mmmmmmm mmmmmm mmm mmmm\'m mmmmm mmmm mmmmmmm.",ep:0,g:18,l:1,wd:true,fm:true,w:0,m:true,p:0};
I.u[10675] = {n:"Dofusian Present",t:89,d:"We won\'t spoil the surprise and tell you what\'s inside! Just have fun my friend and don\'t party too much!",ep:1,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10676] = {n:"Kill Coos Double Effect",t:28,d:"Your prospecting and your wisdom are increased for a few fights.",ep:0,g:19,l:1,wd:false,fm:true,w:0,m:true,p:0};
I.u[10677] = {n:"Kill Coos Shigekax",t:42,d:"Rediscover the savour and sweetness of the candy of old with this traditionally prepared sweetie.  \nThis candy increases both prospecting and wisdom by 100 points for 20 fights.",ep:0,g:32,l:1,wd:false,fm:true,w:1,c:"PO!10676",u:true,p:1};
I.u[10678] = {n:"How to travel without ever losing your way",t:25,d:"Arpagnagrobis wrote this book for any adventurer who doesn\'t know how to use their compass and Zaaps.",ep:0,g:10,l:1,wd:false,fm:true,w:1,u:true,p:10};
I.u[10679] = {n:"Primitive Potion",t:12,d:"This ethereal potion can only be consumed by the person who finds it. It will strengthen the link between their soul and their body.",ep:0,g:716,l:1,wd:false,fm:true,w:0,c:"Qf=485",u:true,p:1};
I.u[10680] = {n:"Goultarminator\'s Bloody Souvenir",t:24,d:"You tore this still-beating heart out of the body of Goultard\'s Evil Essence. You can now put it on your desk as a souvenir.",ep:0,g:518,l:1,wd:false,fm:true,w:0,p:1};
I.u[10681] = {n:"Prancing Chimera Transformation",t:31,d:"Well done!",ep:0,g:2,l:1,wd:false,fm:false,w:0,m:true,p:0};
I.u[10682] = {n:"Percimol\'s Secret",t:29,d:"Luck and happiness go hand-in-hand.",ep:0,g:5,l:1,wd:false,fm:true,w:0,m:true,p:0};
I.u[10683] = {n:"Visionary Potion",t:12,d:"This potion grants the drinker visionary talents, which allows them to find treasures more easily. Unfortunately, the effect is temporary and lasts only 10 fights.",ep:0,g:716,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10684] = {n:"Visionary Talents",t:29,d:"With these visionary talents you\'ll find treasures more easily. Unfortunately, the effect isn\'t permanent.",ep:0,g:5,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[10685] = {n:"Haks Or Mask",t:16,d:"Equipped with this golden helmet, your head will soon be up for auction and worth its weight in gold.",ep:0,g:254,l:52,wd:false,fm:true,w:10,s:151,p:7325};
I.u[10686] = {n:"Haks Or Cloak",t:17,d:"This fabric cloak, coated with a thin layer of gold, is magical. It attracts attention and reflects light directly into the pupils of dishonest types who try to stab you from behind. Indispensable if you have Sram friends.",ep:0,g:171,l:54,wd:false,fm:true,w:10,s:151,p:7750};
I.u[10687] = {n:"Haks Or Ring",t:9,d:"This ring is so heavy that it greatly increases the inertia of your fist when you distribute blows to your opponents. When you begin punishing peasants, it will be virtually impossible to stop you.",ep:0,g:182,l:51,wd:false,fm:true,w:10,s:151,p:6862};
I.u[10688] = {n:"Haks Or Belt",t:10,d:"This belt is perfect to hang your gold bars around your waist, they\'ll pass unnoticed.",ep:0,g:166,l:53,wd:false,fm:true,w:10,s:151,p:7525};
I.u[10689] = {n:"Gift: Grute\'s Sword",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10690] = {n:"Gift: Grute\'s Amulet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10691] = {n:"Gift: Grute\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10692] = {n:"Gift: Grute\'s Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10693] = {n:"Gift: Koksiks\' Sword",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10694] = {n:"Gift: Koksiks\' Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10695] = {n:"Gift: Koksiks\' Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10696] = {n:"Gift: Koksiks\' Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10697] = {n:"Gift: Goboff\'s Staff",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10698] = {n:"Gift: Goboff\'s Amulet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10699] = {n:"Gift: Goboff\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10700] = {n:"Gift: Goboff\'s Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10701] = {n:"Gift: Lektor\'s Bow",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10702] = {n:"Gift: Lektor\'s Amulet",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10703] = {n:"Gift: Lektor\'s Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10704] = {n:"Gift: Lektor\'s Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10705] = {n:"Gift: Stroy Zemol\'s Sword",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10706] = {n:"Gift: Stroy Zemol\'s Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10707] = {n:"Gift: Stroy Zemol\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10708] = {n:"Gift: Stroy Zemol\'s Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10709] = {n:"Gift: Fyred Ampe\'s Pickaxe",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10710] = {n:"Gift: Fyred Ampe\'s Ring",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10711] = {n:"Gift: Fyred Ampe\'s Boots",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10712] = {n:"Gift: Fyred Ampe\'s Belt",t:89,d:"If you shake this gift box vigorously, you\'ll find it\'s not empty. For once, the gods might not have been pulling your leg.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10713] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10714] = {n:"",t:24,d:"",ep:0,g:757,l:1,wd:false,fm:true,w:0,p:1};
I.u[10715] = {n:"Creashun Powder",t:48,d:"Following the spell cast by Silouate, the Minotoror Protector of the month of Aperirel, a humble alchemist called Creashun had a flash of genius as to how to save the pets from the plague that was decimating them. While the Protector was napping one day, Creashun took advantage of his slumber to take a sample of his muscle mass and synthesised it to be used at a later date to administer to the pets and make them stronger.",ep:0,g:670,l:1,wd:true,fm:true,w:1,p:100};
I.u[10716] = {n:"Atooin Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:200,l:1,wd:true,fm:true,w:1,p:10};
I.u[10717] = {n:"Pandawa Cub Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:201,l:1,wd:true,fm:true,w:1,p:10};
I.u[10718] = {n:"Bilby Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:202,l:1,wd:true,fm:true,w:1,p:10};
I.u[10719] = {n:"Bwak Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:203,l:1,wd:true,fm:true,w:1,p:10};
I.u[10720] = {n:"Bworky Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:235,l:1,wd:true,fm:true,w:1,p:10};
I.u[10721] = {n:"Bow Meow Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:205,l:1,wd:true,fm:true,w:1,p:10};
I.u[10722] = {n:"Angora Bow Meow Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:206,l:1,wd:true,fm:true,w:1,p:10};
I.u[10723] = {n:"Tabby Bow Meow Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:207,l:1,wd:true,fm:true,w:1,p:10};
I.u[10724] = {n:"Crocodyl Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:208,l:1,wd:true,fm:true,w:1,p:10};
I.u[10725] = {n:"Mischievous Squirrel Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:209,l:1,wd:true,fm:true,w:1,p:10};
I.u[10726] = {n:"Fëanor Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:210,l:1,wd:true,fm:true,w:1,p:10};
I.u[10727] = {n:"Bloody Koalak Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:211,l:1,wd:true,fm:true,w:1,p:10};
I.u[10728] = {n:"Quaquack Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:212,l:1,wd:true,fm:true,w:1,p:10};
I.u[10729] = {n:"Leopardo Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:213,l:1,wd:true,fm:true,w:1,p:10};
I.u[10730] = {n:"Mini Wa Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:214,l:1,wd:true,fm:true,w:1,p:10};
I.u[10731] = {n:"Nomoon Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:215,l:1,wd:true,fm:true,w:1,p:10};
I.u[10732] = {n:"Peki Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:216,l:1,wd:true,fm:true,w:1,p:10};
I.u[10733] = {n:"Little White Bow Meow Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:217,l:1,wd:true,fm:true,w:1,p:10};
I.u[10734] = {n:"Little Black Bow Wow Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:218,l:1,wd:true,fm:true,w:1,p:10};
I.u[10735] = {n:"Piwin Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:219,l:1,wd:true,fm:true,w:1,p:10};
I.u[10736] = {n:"Ross Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:220,l:1,wd:true,fm:true,w:1,p:10};
I.u[10737] = {n:"Baby Crowdzilla Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:221,l:1,wd:true,fm:true,w:1,p:10};
I.u[10738] = {n:"Wabbit Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:222,l:1,wd:true,fm:true,w:1,p:10};
I.u[10739] = {n:"Pingoku Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:223,l:1,wd:true,fm:true,w:1,p:10};
I.u[10740] = {n:"Willy Peninzias Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:224,l:1,wd:true,fm:true,w:1,p:10};
I.u[10741] = {n:"Young Wild Boar Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:225,l:1,wd:true,fm:true,w:1,p:10};
I.u[10742] = {n:"Miniminotot Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:226,l:1,wd:true,fm:true,w:1,p:10};
I.u[10743] = {n:"Tiwabbit Wosungwee Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:227,l:1,wd:true,fm:true,w:1,p:10};
I.u[10744] = {n:"Borbat Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:228,l:1,wd:true,fm:true,w:1,p:10};
I.u[10745] = {n:"Black Dragoone Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:229,l:1,wd:true,fm:true,w:1,p:10};
I.u[10746] = {n:"Godfather\'s Gobtubby Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:230,l:1,wd:true,fm:true,w:1,p:10};
I.u[10747] = {n:"Jellufo Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:231,l:1,wd:true,fm:true,w:1,p:10};
I.u[10748] = {n:"Rushu\'s Shushu Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:232,l:1,wd:true,fm:true,w:1,p:10};
I.u[10749] = {n:"Vampyrina Hormone",t:48,d:"This dehydrated growth hormone can be used to make a powerful potion to improve a pet\'s characteristics.",ep:0,g:233,l:1,wd:true,fm:true,w:1,p:10};
I.u[10750] = {n:"Enhancement Potion: Atooin",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:20,l:1,wd:true,fm:true,w:1,c:"PO=7714",u:true,p:10};
I.u[10751] = {n:"Enhancement Potion: Pandawa Cub",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:21,l:1,wd:true,fm:true,w:1,c:"PO=8561",u:true,p:10};
I.u[10752] = {n:"Enhancement Potion: Bilby",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:22,l:1,wd:true,fm:true,w:1,c:"PO=7706",u:true,p:10};
I.u[10753] = {n:"Enhancement Potion: Bwak",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:23,l:1,wd:true,fm:true,w:1,c:"PO=2074|PO=2075|PO=2076|PO=2077",u:true,p:10};
I.u[10754] = {n:"Enhancement Potion: Bworky",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:24,l:1,wd:true,fm:true,w:1,c:"PO=8000",u:true,p:10};
I.u[10755] = {n:"Enhancement Potion: Bow Meow",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:25,l:1,wd:true,fm:true,w:1,c:"PO=1728",u:true,p:10};
I.u[10756] = {n:"Enhancement Potion: Angora Bow Meow",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:26,l:1,wd:true,fm:true,w:1,c:"PO=9617",u:true,p:10};
I.u[10757] = {n:"Enhancement Potion: Tabby Bow Meow",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:27,l:1,wd:true,fm:true,w:1,c:"PO=7524",u:true,p:10};
I.u[10758] = {n:"Enhancement Potion: Crocodyl",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:28,l:1,wd:true,fm:true,w:1,c:"PO=9623",u:true,p:10};
I.u[10759] = {n:"Enhancement Potion: Mischievous Squirrel",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:29,l:1,wd:true,fm:true,w:1,c:"PO=7704",u:true,p:10};
I.u[10760] = {n:"Enhancement Potion: Fëanor",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:30,l:1,wd:true,fm:true,w:1,c:"PO=8693",u:true,p:10};
I.u[10761] = {n:"Enhancement Potion: Bloody Koalak",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:31,l:1,wd:true,fm:true,w:1,c:"PO=7911",u:true,p:10};
I.u[10762] = {n:"Enhancement Potion: Quaquack",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:32,l:1,wd:true,fm:true,w:1,c:"PO=6604",u:true,p:10};
I.u[10763] = {n:"Enhancement Potion: Leopardo",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:33,l:1,wd:true,fm:true,w:1,c:"PO=7705",u:true,p:10};
I.u[10764] = {n:"Enhancement Potion: Mini Wa",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:34,l:1,wd:true,fm:true,w:1,c:"PO=7891",u:true,p:10};
I.u[10765] = {n:"Enhancement Potion: Nomoon",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:35,l:1,wd:true,fm:true,w:1,c:"PO=6716",u:true,p:10};
I.u[10766] = {n:"Enhancement Potion: Peki",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:36,l:1,wd:true,fm:true,w:1,c:"PO=6978",u:true,p:10};
I.u[10767] = {n:"Enhancement Potion: Little White Bow Meow",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:37,l:1,wd:true,fm:true,w:1,c:"PO=7414",u:true,p:10};
I.u[10768] = {n:"Enhancement Potion: Little Black Bow Wow",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:38,l:1,wd:true,fm:true,w:1,c:"PO=7415",u:true,p:10};
I.u[10769] = {n:"Enhancement Potion: Piwin",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:39,l:1,wd:true,fm:false,w:1,c:"PO=7708|PO=7709|PO=7710|PO=7711|PO=7712|PO=7713",u:true,p:10};
I.u[10770] = {n:"Enhancement Potion: Ross",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:40,l:1,wd:true,fm:true,w:1,c:"PO=8677",u:true,p:10};
I.u[10771] = {n:"Enhancement Potion: Baby Crowdzilla",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:41,l:1,wd:true,fm:true,w:1,c:"PO=7703",u:true,p:10};
I.u[10772] = {n:"Enhancement Potion: Wabbit",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:42,l:1,wd:true,fm:true,w:10,c:"PO=1748",u:true,p:10};
I.u[10773] = {n:"Enhancement Potion: Pingoku",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:43,l:1,wd:true,fm:true,w:1,c:"PO=8211",u:true,p:10};
I.u[10774] = {n:"Enhancement Potion: Willy Peninzias",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:44,l:1,wd:true,fm:true,w:1,c:"PO=7892",u:true,p:10};
I.u[10775] = {n:"Enhancement Potion: Young Wild Boar",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:45,l:1,wd:true,fm:true,w:1,c:"PO=7707",u:true,p:10};
I.u[10776] = {n:"Enhancement Potion: Miniminotot",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:46,l:1,wd:true,fm:true,w:1,c:"PO=9620",u:true,p:10};
I.u[10777] = {n:"Enhancement Potion: Tiwabbit Wosungwee",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:47,l:1,wd:true,fm:true,w:1,c:"PO=9619",u:true,p:10};
I.u[10778] = {n:"Enhancement Potion: Borbat",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:48,l:1,wd:true,fm:true,w:1,c:"PO=10107",u:true,p:10};
I.u[10779] = {n:"Enhancement Potion: Black Dragoone",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:49,l:1,wd:true,fm:true,w:1,c:"PO=9624",u:true,p:10};
I.u[10780] = {n:"Enhancement Potion: Godfather\'s Gobtubby",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:50,l:1,wd:true,fm:true,w:1,c:"PO=9594",u:true,p:10};
I.u[10781] = {n:"Enhancement Potion: Jellufo",t:116,d:"Using this powerful potion will increase the capacity of your pet permanently. Be careful though, only one dose will work. Trying more than once will cause disappointing results.",ep:0,g:51,l:1,wd:true,fm:true,w:1,c:"PO=10544",u:true,p:10};
