I.u[10809] = {n:"Pócima de mejora de dragún dorado",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:59,l:1,wd:true,fm:true,w:1,c:"PO=10802",u:true,p:10};
I.u[10810] = {n:"Hormona de buscador de ogrinas",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:234,l:1,wd:false,fm:true,w:1,p:10};
I.u[10811] = {n:"Pócima de mejora de buscador de ogrinas",t:116,d:"Utilizando esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota solamente puede asimilar una dósis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:54,l:1,wd:true,fm:true,w:1,c:"PO=10657",u:true,p:10};
I.u[10812] = {n:"Mensaje anónimo",t:24,d:"«Si buscas un trabajo fácil y bien pagado, ven a verme al norte de la ciudad, al este de la estatua de Sram. Ven solo.»",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[10813] = {n:"Lista de nombres",t:24,d:"Encontraste esta lista en la casa de Prandacilla Dragcuin. Parece que se trata de pandawas.",ep:0,g:74,l:1,wd:false,fm:true,w:0,p:1};
I.u[10814] = {n:"Caja para Pandilla",t:24,d:"Debes llevarle esta caja a Pandilla, que estará en el pueblo de Akwadala. No tienes ni idea de lo que puede haber dentro.",ep:0,g:44,l:1,wd:false,fm:true,w:0,p:1};
I.u[10815] = {n:"Líquido extraño",t:24,d:"Essel Dawa te ha pedidio que solicites la ayuda de Mago de Zo para analizar este líquido.",ep:0,g:32,l:1,wd:false,fm:true,w:0,p:1};
I.u[10816] = {n:"Pétalo marchito de rosa demoníaca",t:24,d:"Este pétalo arrugado ha perdido su esplendor. De hecho, su textura actual recuerda a la piel de los anutrofs.",ep:0,g:817,l:1,wd:false,fm:true,w:0,p:1};
I.u[10817] = {n:"Anti-adicción",t:24,d:"Este prototipo de antidoto deberia poder curar la adiccion al zumo de stropajo.",ep:0,g:500,l:1,wd:false,fm:true,w:0,p:1};
I.u[10818] = {n:"Hacha de novato",t:19,d:"Esta arma, aparentemente rudimentaria, te dará la impresión de saber luchar.",ep:0,g:1,l:1,wd:true,fm:true,w:10,an:17,e:[5,4,1,1,50,50,false,false],p:1};
I.u[10825] = {n:"Ghulificado",t:30,d:"¿Tantos esfuerzos para acabar así?",ep:0,g:1,l:1,wd:false,fm:true,w:0,m:true,p:0};
I.u[10826] = {n:"Orden de exulsión",t:24,d:"Como no te has portado bien con tu anfitrión, ha decidido cerrarte el acceso a su cripta durante las próximas 24 horas.",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:0};
I.u[10827] = {n:"Pócima de curación larvesca",t:12,d:"Un líquido anaranjado y burbujeante. ¿Quién podría beberse algo así?",ep:0,g:192,l:1,wd:true,fm:true,w:1,c:"Sc=7",u:true,ut:true,p:0};
I.u[10828] = {n:"Casco de jálabol",t:16,d:"Se dice que el ridículo nunca mato a nadie. Cierto, pero con este casco parecerás realmente ridículo.",ep:0,g:253,l:29,wd:false,fm:true,w:10,c:"Sc=10",p:2400};
I.u[10829] = {n:"Caña Peskamas",t:20,d:"Gracias a este bastón, saldrás ganando en todos los regateos.",ep:0,g:91,l:40,wd:false,fm:true,w:10,an:12,e:[7,3,1,1,40,50,false,false],c:"Sc=13",p:4200};
I.u[10830] = {n:"Capa banana",t:17,d:"¿Llevas una capa banana en el bolsillo o es sólo que te alegras de verme?",ep:0,g:172,l:28,wd:false,fm:true,w:10,c:"Sc=14",p:2305};
I.u[10831] = {n:"Bananaranja",t:46,d:"Flambeada o en rodajas, bañada de chocolate o al natural, esta fruta es un postre delicioso, la tomes como la tomes.",ep:0,g:1,l:1,wd:true,fm:true,w:1,p:1};
I.u[10832] = {n:"Crujirroca",t:94,d:"Esta brillante piedra encierra un crujibola de pocas luces. Pareece que sólo podrás utilizarla cerca de otros cruijdores o crujibolas...",ep:0,g:18,l:1,wd:false,fm:true,w:20,c:"Sc=15&(PB=2|PB=96|PB=480)",u:true,p:0};
I.u[10833] = {n:"Miaullleta",t:33,d:"Esta galleta es muy extraña: cuando la muerdes, ¡maulla!",ep:0,g:4,l:1,wd:false,fm:true,w:2,c:"Sc=16",u:true,ut:true,p:0};
I.u[10834] = {n:"Ushanka Guau",t:16,d:"Tampoco necesitas gran cosa para parecerte a un uginak. ¡Cuidado con las pulgas!",ep:0,g:256,l:11,wd:false,fm:true,w:10,c:"Sc=17",p:530};
I.u[10835] = {n:"Marca de novato",t:50,d:"Pisoteado, mordisqueado, aplastado, lavado, secado y planchado. Te las han dado por todos lados. Ya no sólo te duele el cuerpo, ¡te duele hasta el ego!",ep:0,g:707,l:1,wd:false,fm:true,w:1,p:0};
I.u[10836] = {n:"Jalaboleto",t:1,d:"Llevas con orgullo este amuleto, símbolo de tu participación en esta gran manifestación deportiva. Es lo minimo para conservar un poco de orgullo después de haber acabado bajo la melé del J.C. Trool.",ep:0,g:158,l:64,wd:false,fm:true,w:1,c:"Sc=18",p:11765};
I.u[10838] = {n:"Anaranjado",t:30,d:"¡Esto te pasa por beber cosas raras sin saber lo que hay dentro!",ep:0,g:1,l:1,wd:false,fm:true,w:0,m:true,p:0};
I.u[10839] = {n:"Don Bollo",t:33,d:"Uno puede dejarse los dientes en un bollo si está muy duro. Si quieres probarlo, ¡allá tú!",ep:0,g:12,l:1,wd:false,fm:true,w:100,c:"Sc=8",u:true,p:0};
I.u[10840] = {n:"Don Bollo comestible",t:33,d:"Esté esta más blando. ¡Qué aproveche!",ep:0,g:12,l:1,wd:true,fm:true,w:1,c:"Sc=8",u:true,ut:true,p:0};
I.u[10841] = {n:"Marrón",t:30,d:"¿Nadie te avisó de los efectos secundarios?",ep:0,g:1,l:1,wd:true,fm:true,w:0,m:true,p:0};
I.u[10842] = {n:"Transformación en miaumiau",t:31,d:"Tenía que pasar y ha pasado. ¡Ahora no vengas quejándote cuando vomites bolas de pelos!",ep:0,g:21,l:1,wd:false,fm:false,w:0,m:true,c:"Sc=16",p:0};
I.u[10843] = {n:"Nota sobre Krtek",t:24,d:"Has anotado a qué hora fue la paliza a Krtek. Así, sabrás cuándo volver para darle otra.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10844] = {n:"Mmmmm",t:31,d:"Mmmmm mm mmmmmm mmmmm, mmm mmm mm mmmmmm mmmmm mmmmmmm mmmmmm mmm mmmmm mmmmm mmmm mmmmmmm.",ep:0,g:19,l:1,wd:true,fm:false,w:0,m:true,p:1};
I.u[10846] = {n:"Ferocapa",t:17,d:"Cada vez que te cruzas con un tofu quiere frotarse contra tu pierna como si estuviese preso de un extraño frenesí. ¿No será esta capa la que les atrae?",ep:0,g:173,l:61,wd:false,fm:true,w:10,c:"Sc=19",p:9700};
I.u[10847] = {n:"Botas de Ravelaca",t:11,d:"Ravelaca se ponía estas botas una vez al año, pero se las quitaba todos los días al acostarse. De esto se deduce que estas botas son mágicas.",ep:0,g:151,l:53,wd:true,fm:true,w:10,s:152,p:7400};
I.u[10848] = {n:"Botas de Kunye",t:11,d:"Estas botas tan coquetas pueden servirte de yunque. Su anterior propietario te recomienda que no bailes con ellas.",ep:0,g:152,l:52,wd:false,fm:true,w:10,s:153,p:7175};
I.u[10849] = {n:"Cinturón de Ravelaca",t:10,d:"Este cinturón fue fabricado sobre un armazón metálico imantado que atrae las bolsas de los imprudentes que osan acercarse demasiado.",ep:0,g:169,l:51,wd:true,fm:true,w:10,s:152,p:6825};
I.u[10850] = {n:"Cinturón de Kunye",t:10,d:"Kunye tenía muchas debilidades: las araknas, las cosquillas, y las araknas cosquillosas.",ep:0,g:167,l:52,wd:false,fm:true,w:10,s:153,p:7100};
I.u[10851] = {n:"Cinturón de Napazam",t:10,d:"Este cinturón aún está recubierto de harina. Quizás porque Napazam, el panadero oscuro, lo utilizaba como delantal. Esperemos que no sea la harina con la que se enharinaba el trasero.",ep:0,g:168,l:51,wd:false,fm:true,w:10,s:154,p:6928};
I.u[10852] = {n:"Amuleto de Ravelaca",t:1,d:"Ravelaca le robó este amuleto a Odirruba, un goblin al que no le hacía gracia ningún chiste (ni siquiera los buenos).",ep:0,g:156,l:53,wd:true,fm:true,w:10,s:152,p:7405};
I.u[10853] = {n:"Amuleto de Napazam",t:1,d:"Con este amuleto podrás amasarte la piel del cuello sin utilizar las manos.",ep:0,g:155,l:53,wd:false,fm:true,w:10,s:154,p:7400};
I.u[10854] = {n:"Anillo de Kunye",t:9,d:"Kunye, el herrero, cambio este anillo por un espada que perteneció a Dam Antium.",ep:0,g:183,l:54,wd:false,fm:true,w:10,s:153,p:7650};
I.u[10855] = {n:"Anillo de Napazam",t:9,d:"Este anillo lo han introducido en una mezcla de una gran cantidad de levaduras diferentes y hasta se dice que tiene la capacidad de transformar en moho a aquellos que lo lucen. Pero algunos aventureros no ven el cambio...",ep:0,g:184,l:51,wd:false,fm:true,w:10,s:154,p:6975};
I.u[10856] = {n:"Hacha de Ravelaca",t:19,d:"Ravelaca era un pésimo bandido al que le remordía la conciencia y por eso tenía que devolver todo lo que robaba. El alma del bandido Ravelaca está aún impregnada en esta arma mágica. Si la equipas, quizás consigas encarnarte en él.",ep:0,g:58,l:47,wd:true,fm:false,w:10,an:17,e:[5,4,1,1,40,50,false,false],s:152,p:5900};
I.u[10857] = {n:"Martillo de Kunye",t:7,d:"Con este martillo se forjó una bragueta de kriptonita para el capitán Chafer. El alma del herrero oscuro Kunye esta aún impregnada en esta arma. Si la equipas, quizás te encarnes en él.",ep:0,g:724,l:51,wd:false,fm:false,w:10,an:15,e:[5,4,1,1,40,50,false,false],s:153,p:7000};
I.u[10858] = {n:"Vaguita de Napazam",t:3,d:"El célebre francés Napazam solía decir: «La mejog manega de gesolveg los pgoblemas es gepagtig pan pan panes. Con mi vaguita impondgé ogden». Y lo cierto es que se servía de esta arma para castigar a los inocentes. La magia de Napazam, el panadero oscuro, está aún impregnada en este arma. Quizás consigas encarnarte en él al utilizarla.",ep:0,g:73,l:53,wd:false,fm:false,w:10,an:11,e:[5,4,3,5,50,50,false,false],s:154,p:5000};
I.u[10860] = {n:"Pócima de cambio de nombre",t:12,d:"Con esta pócima podrás cambiar de nombre, así ya nadie se acordará de que hubo un tiempo en que te llamaste Xx-naruto-killer-feca-xX. Podrás disfrutar de una nueva vida, sin bromas de mal gusto, y por fin llegar a ser alguien.",ep:0,g:718,l:1,wd:false,fm:true,w:0,u:true,p:0};
I.u[10861] = {n:"Pócima de cambio de colores",t:12,d:"En la etiqueta se puede leer: «¿Cansado de que te traten de viejo verde? ¿Te gustaria que te vieran como a un príncipe azúl? ¡¡Pues no lo pienses más y usa esta pócima!!».",ep:0,g:717,l:1,wd:false,fm:true,w:0,u:true,p:0};
I.u[10862] = {n:"Pócima de cambio de sexo",t:12,d:"Esta pócima, que se bebe a morro, te hará que seas él si eres ella o que seas ella si eres él.\n¡Atención! El abuso de su consumo no perjudica la salud.",ep:0,g:719,l:1,wd:false,fm:true,w:0,u:true,p:0};
I.u[10863] = {n:"Araknuza",t:18,d:"Esta arakna es realmente malvada, insulta, grita, salta por todos lados y hasta morderá a quien se descuide, pero tú la quieres mucho aunque no sepas por qué. La naturaleza la ha dotado de un apetito feroz, a este devorador de almas le encanta atacar y a los moskitos y a las larvas.",ep:0,g:58,l:1,wd:true,fm:true,w:1,c:"PZ=1",p:1};
I.u[10864] = {n:"Miscaludo",t:18,d:"Éste no es un champi champ como los demás. Se crió  junto a una jauría de mediulubos, aunque eso no explica por qué tiene tantos pelos en el sobaco... A este devorador de almas le encanta el marisco y sólo comerá criaturas de las playas.",ep:0,g:59,l:1,wd:true,fm:true,w:1,c:"PZ=1",p:1};
I.u[10865] = {n:"Tofucilazo",t:18,d:"A este tofu ya le han caído 11 rayos en la cabeza. Si lo acaricias te dará calambres, pero si no lo acaricias, es capaz de fulminarte... ¡Tú eliges! Este devorador de almas odia a las ratas y se las zampa en cuanto se le presenta la ocasión.",ep:0,g:60,l:1,wd:true,fm:true,w:1,c:"PZ=1",p:1};
I.u[10866] = {n:"Otazo",t:18,d:"A esta mascota le gustan las alcachofas con sangre de rasgabola, las endivias con pelos de tufo y las canciones de Badiz Mustabante. También parece gustarle tu compañía. Este devorador de almas sólo se alimenta de las criaturas de La Oscura Jungla.",ep:0,g:61,l:1,wd:true,fm:true,w:1,c:"PZ=1",p:1};
I.u[10867] = {n:"Fantasma de araknuza",t:90,d:"Esta araknuza aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o de abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:57,l:1,wd:true,fm:true,w:1,p:1};
I.u[10868] = {n:"Fantasma de miscaludo",t:90,d:"Este miscaludo aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o de abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:59,l:1,wd:true,fm:true,w:1,p:1};
I.u[10869] = {n:"Fantasma de tofucilazo",t:90,d:"Este tofucilazo aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o de abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:58,l:1,wd:true,fm:true,w:1,p:1};
I.u[10870] = {n:"Fantasma de otazo",t:90,d:"Este otazo aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o de abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:60,l:1,wd:true,fm:true,w:1,p:1};
I.u[10871] = {n:"Regalo: araknuza",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10872] = {n:"Regalo: miscaludo",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10873] = {n:"Regalo: tofucilazo",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10874] = {n:"Regalo: otazo",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti.",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[10875] = {n:"Certificado de admisión en la petrera: araknuza",t:77,d:"Este certificado describe las características de la araknuza que has dejado en la petrera.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10876] = {n:"Certificado de admisión en la petrera: miscaludo",t:77,d:"Este certificado describe las características del miscaludo que has dejado en la petrera.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10877] = {n:"Certificado de admisión en la petrera: tofucilazo",t:77,d:"Este certificado describe las características del tofucilazo que has dejado en la petrera.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10878] = {n:"Certificado de admisión en la petrera: otazo",t:77,d:"Este certificado describe las características del otazo que has dejado en la petrera.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[10879] = {n:"Hormona de araknuza",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:236,l:1,wd:true,fm:true,w:1,p:10};
I.u[10880] = {n:"Hormona de miscaludo",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:238,l:1,wd:true,fm:true,w:1,p:10};
I.u[10881] = {n:"Hormona de tofucilazo",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:237,l:1,wd:true,fm:true,w:1,p:10};
I.u[10882] = {n:"Hormona de otazo",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:239,l:1,wd:true,fm:true,w:1,p:10};
I.u[10883] = {n:"Pócima de mejora de araknuza",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:56,l:1,wd:true,fm:true,w:1,c:"PO=10863",u:true,p:10};
I.u[10884] = {n:"Pócima de mejora de miscaludo",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:58,l:1,wd:true,fm:true,w:1,c:"PO=10864",u:true,p:10};
I.u[10885] = {n:"Pócima de mejora de tofucilazo",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:57,l:1,wd:true,fm:true,w:1,c:"PO=10865",u:true,p:10};
I.u[10886] = {n:"Pócima de mejora de otazo",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:55,l:1,wd:true,fm:true,w:1,c:"PO=10866",u:true,p:10};
I.u[10887] = {n:"Regalo: amuleto de Ravelaca",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10888] = {n:"Regalo: amuleto de Napazam",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10889] = {n:"Regalo: vaguita de Napazam",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10890] = {n:"Regalo: martillo de Kunye",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10891] = {n:"Regalo: hacha de Ravelaca",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10892] = {n:"Regalo: anillo de Kunye",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10893] = {n:"Regalo: anillo de Napazam",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10894] = {n:"Regalo: cinturón de Ravelaca",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10895] = {n:"Regalo: cinturón de Kunye",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10896] = {n:"Regalo: cinturón de Napazam",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10897] = {n:"Regalo: botas de Ravelaca",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10898] = {n:"Regalo: botas de Kunye",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este Regalo: sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10899] = {n:"Bastón del zoth Manitú",t:4,d:"El zoth Manitú fue funcionario, aplazaba los problemas en lugar de resolverlos. Pero poco importa porque todos los zoths le temían: gritaba más fuerte que ningún otro, y eso es suficiente para ser jefe de los zoths. El alma de Manitú está aún impregnada en este bastón. Quizás puedas encarnarte en él cuando lo utilices.",ep:0,g:91,l:50,wd:false,fm:false,w:10,an:12,e:[5,3,1,1,40,50,false,false],p:6000};
I.u[10900] = {n:"Trozo de cáscara",t:24,d:"Tienes en tu mano uno de los restos de aquellos gigantescos cascarones que salieron en la penínsulita de los dragohuevos. Ni siquiera sirve como cenicero.",ep:0,g:767,l:1,wd:false,fm:true,w:0,p:0};
I.u[10901] = {n:"Colmillo gigante",t:24,d:"Grasmera y Grozilla participaron en un combate épico. Todo lo que ahora queda de ellos es este gigantesco canino. ¿Quién habría creído que tú estuviste presente en el combate?",ep:0,g:13,l:1,wd:false,fm:true,w:0,p:0};
I.u[10902] = {n:"Tanga del zoth Manitú",t:24,d:"Ahora puedes decir sin temor a equivocarte que el zoth Manitú anda en cueros sin su taparrabos.",ep:0,g:621,l:1,wd:false,fm:true,w:0,p:1};
I.u[10903] = {n:"Llave del antro del zoth Manitú",t:24,d:"Esta llave te abrirá la puerta para luchar contra el zoth Manitú.",ep:0,g:790,l:1,wd:false,fm:true,w:0,p:1};
I.u[10904] = {n:"Grozillamu",t:1,d:"Este amuleto demuestra tu indudable capacidad para romper los huevos sin hacerlos tortilla.",ep:0,g:157,l:51,wd:false,fm:true,w:10,p:7050};
I.u[10906] = {n:"Escudo dragónico",t:82,d:"Este escudo está hecho con una escama de Grozilla, es muy pesado pero tiene una calidad excepcional. Sólo los luchadores más increíbles pueden lucir este gran escudo.",ep:0,g:51,l:1,wd:false,fm:false,w:10,p:0};
I.u[10908] = {n:"Regalo: del beta-test de mazmorras de DOFUS 2.0",t:89,d:"Te has ganado este Regalo: por haber pasado más tiempo en las mazmorras de la beta de DOFUS 2.0 que el común de los mortales.",ep:0,g:42,l:1,wd:false,fm:true,w:0,u:true,p:1};
I.u[10909] = {n:"Feromona de tofu",t:48,d:"Esta feromona disecada y en polvo, podría atraer a un tofu a kilómetros de distancia...¡si tus propias feromonas no lo asfixian antes!",ep:0,g:241,l:1,wd:false,fm:true,w:1,p:1};
I.u[10910] = {n:"Regalo: DOFUS 2.0 edición de coleccionista",t:89,d:"¡IMPORTANTE! ESTE Regalo: SÓLO PUEDES ABRIRLO EN UN SERVIDOR DOFUS 2.0.\nEste set te volverá hasta inteligente, a condición de que no digas ni \"mu\". Y si no funciona, por lo menos servirá para que impresiones a las habitantes de Astrub.",ep:0,g:42,l:1,wd:false,fm:true,w:0,u:true,p:1};
I.u[10911] = {n:"Pócima de recuerdo de Mr. Scuty",t:12,d:"La «Pócima de recuerdo de Mr. Scuty», que es mucho más untuosa y sabrosa que una pócima de recuerdo clásica, te llevará al zaap de Astrub sin importar donde estés. Su doble efecto te garantiza un uso más prolongado y que dura más, mucho más tiempo.\nLa «Pócima de recuerdo de Mr. Scuty» es una marca registrada, propieda de las empresas Kyrc & Spuky.",ep:0,g:26,l:1,wd:false,fm:false,w:0,c:"Sc=666",u:true,p:0};
I.u[10912] = {n:"Regalo: de Nawidad porquería",t:89,d:"No todos los regalos de Nawidad tienen el mismo tamaño. Los aventureros que no han sabido ser lo suficientemente temerarios se llevan a casa una porquería de regalos y el derecho a llorar por haber sido el blanco de todas las burlas.",ep:0,g:2,l:6,wd:false,fm:true,w:10,u:true,p:1};
I.u[10913] = {n:"Regalo: de Nawidad normalucho",t:89,d:"El que hizo este Regalo: no se esmeró demasiado. «Con que sea nomaluscho bastará» -se decía a si mismo.",ep:0,g:2,l:7,wd:false,fm:true,w:20,u:true,p:1};
I.u[10914] = {n:"Regalo: de Nawidad potencialmente superpoderoso",t:89,d:"Según pone en la etiqueta sujeta con el lazito, éste puede ser un gran regalo. Sin embargo, todos los aventureros te dirán que nunca hay que fiarse en lo que pone en las etiquetas de los lazitos.",ep:0,g:2,l:8,wd:false,fm:true,w:30,u:true,p:1};
I.u[10915] = {n:"Órdenes de misión de Félix Nawidad",t:24,d:"Félix Nawidad te ha desvelado la identidad de uno de los ladrones del almacen de Papá Nowel. Si no consigues vencerlo en las siguientes dos horas, podrás volver a ver a Félix Nawidad para que te dé nuevas órdenes de misión.",ep:0,g:33,l:1,wd:false,fm:true,w:0,p:1};
I.u[10916] = {n:"Agradecimiento de Félix Nawidad",t:24,d:"Félix Nowel ha apreciado tu victoria y te da las gracias. Vuelve a verlo dentro de 24 horas, volverá a necesitar tu ayuda si no ha recuperado todas las cajas.",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[10917] = {n:"Caja pequeña de regalos",t:24,d:"Esta cajita llega directamente del almacén de Papá Nowel. Si se la devuelves a su dueño, serás un héroe.",ep:0,g:44,l:1,wd:false,fm:true,w:0,p:1};
I.u[10918] = {n:"Caja de regalos",t:24,d:"Esta caja llega directamente del almacén de Papá Nowel. Si se la devuelves a su dueño, serás un héroe.",ep:0,g:44,l:1,wd:false,fm:true,w:0,p:1};
I.u[10919] = {n:"Caja grande de regalos",t:24,d:"Esta gran caja llega directamente del almacén de Papá Nowel. Si se la devuelves a su dueño, serás un héroe.",ep:0,g:44,l:1,wd:false,fm:true,w:0,p:1};
I.u[10920] = {n:"Galletas de Nawidad",t:24,d:"Éstas sí que son una galletas preparadas con amor y esmero. Una pena que no puedas probarlas.",ep:0,g:245,l:1,wd:false,fm:true,w:0,p:1};
I.u[10921] = {n:"Regalo: sellado del Minotobola",t:24,d:"Nadie sabe lo que contiene este regalo, el Minotobola se llevó el secreto a la tumba. ¿Hay que recordarte que es culpa tuya? La verdad es que te portaste como un boludo...",ep:0,g:715,l:1,wd:false,fm:true,w:0,p:1};
I.u[10922] = {n:"Escudo del leñador primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=2,100",p:1};
I.u[10923] = {n:"Escudo del forjador de espadas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=11,100",p:1};
I.u[10924] = {n:"Escudo del escultor de arcos primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=13,100",p:1};
I.u[10925] = {n:"Escudo del forjador de martillos primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=14,100",p:1};
I.u[10926] = {n:"Escudo del zapatero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=15,100",p:1};
I.u[10927] = {n:"Escudo del joyero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=16,100",p:1};
I.u[10928] = {n:"Escudo del forjador de dagas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=17,100",p:1};
I.u[10929] = {n:"Escudo del escultor de bastones primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=18,100",p:1};
I.u[10930] = {n:"Escudo del escultor de varitas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=19,100",p:1};
I.u[10931] = {n:"Escudo del forjador de palas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=20,100",p:1};
I.u[10932] = {n:"Escudo del minero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=24,100",p:1};
I.u[10933] = {n:"Escudo del panadero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=25,100",p:1};
I.u[10934] = {n:"Escudo del alquimista primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=26,100",p:1};
I.u[10935] = {n:"Escudo del sastre primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=27,100",p:1};
I.u[10936] = {n:"Escudo del campesino primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=28,100",p:1};
I.u[10937] = {n:"Escudo del forjador de hachas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=31,100",p:1};
I.u[10938] = {n:"Escudo del pescador primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=36,100",p:1};
I.u[10939] = {n:"Escudo del cazador primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=41,100",p:1};
I.u[10940] = {n:"Escudo del forjamago de dagas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=43,100",p:1};
I.u[10941] = {n:"Escudo del forjamago de espadas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=44,100",p:1};
I.u[10942] = {n:"Escudo del forjamago de martillos primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=45,100",p:1};
I.u[10943] = {n:"Escudo del forjamago de palas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=46,100",p:1};
I.u[10944] = {n:"Escudo del forjamago de hachas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=47,100",p:1};
I.u[10945] = {n:"Escudo del escultomago de arcos primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=48,100",p:1};
I.u[10946] = {n:"Escudo del escultomago de varitas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=49,100",p:1};
I.u[10947] = {n:"Escudo del escultomago de bastones primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=50,100",p:1};
I.u[10948] = {n:"Escudo del carnicero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=56,100",p:1};
I.u[10949] = {n:"Escudo del pescadero primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=58,100",p:1};
I.u[10950] = {n:"Escudo del herrero de escudos primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=60,100",p:1};
I.u[10951] = {n:"Escudo del zapateromago primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=62,100",p:1};
I.u[10952] = {n:"Escudo del joyeromago primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=63,100",p:1};
I.u[10953] = {n:"Escudo del sastremago primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=64,100",p:1};
I.u[10954] = {n:"Escudo del manitas primordial",t:82,d:"Con este escudo podrás demostrar a todos los aventureros que eres un pionero en el ejercicio de tu oficio.",ep:0,g:57,l:1,wd:false,fm:true,w:10,c:"PJ=65,100",p:1};
I.u[10955] = {n:"",t:9,d:"",ep:0,g:188,l:33,wd:false,fm:true,w:10,s:155,p:3150};
I.u[10956] = {n:"",t:11,d:"",ep:0,g:158,l:32,wd:false,fm:true,w:10,s:155,p:2850};
I.u[10957] = {n:"",t:17,d:"",ep:0,g:174,l:35,wd:false,fm:true,w:10,s:155,p:3400};
I.u[10958] = {n:"",t:16,d:"",ep:0,g:259,l:32,wd:false,fm:true,w:10,s:155,p:2900};
I.u[10959] = {n:"Epicuervoja, la espada de El Cuervo Negro",t:6,d:"Casi sales desplumado, pero al final ¡la has conseguido! Tuya es Epicuervoja, la legendaria espada de El Cuervo Negro",ep:0,g:98,l:39,wd:false,fm:true,w:10,an:14,e:[13,5,1,1,40,50,false,false],c:"CA>60&CV>60",s:155,p:4400};
I.u[10960] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10961] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10962] = {n:"",t:4,d:"",ep:0,g:92,l:30,wd:false,fm:false,w:10,an:12,e:[6,3,1,1,50,50,false,false],c:"CV>30",s:156,p:2650};
I.u[10963] = {n:"",t:11,d:"",ep:0,g:156,l:32,wd:false,fm:true,w:10,s:156,p:2900};
I.u[10964] = {n:"",t:10,d:"",ep:0,g:172,l:31,wd:false,fm:true,w:10,s:156,p:2800};
I.u[10965] = {n:"",t:1,d:"",ep:0,g:160,l:31,wd:false,fm:true,w:10,s:156,p:2800};
I.u[10966] = {n:"Transformación en larva",t:31,d:"Las malas lenguas insinuarían que se ha despertado tu yo profundo. ¿No tendrán algo de razón?",ep:0,g:19,l:1,wd:false,fm:false,w:0,m:true,c:"Sc=21",p:0};
I.u[10967] = {n:"Sesos de larva",t:69,d:"Hay que estar muy desesperado para comerse esto. ¡No! ¡¡No lo hagas!!",ep:0,g:113,l:1,wd:false,fm:true,w:0,c:"Sc=21",u:true,ut:true,p:1};
I.u[10968] = {n:"Transformación en wabbit",t:31,d:"Por extraño que parezca, no tienes ganas de zanahowia.",ep:0,g:19,l:1,wd:false,fm:false,w:0,m:true,c:"Sc=22",p:0};
I.u[10969] = {n:"Pócima de fwescuwa",t:12,d:"La dulzura de una zanahowia mezclada con la frescura de un dragopavo maratoniano. No encontrarás nada mejor para devolverte la forma. ¡Salud!",ep:0,g:141,l:20,wd:false,fm:true,w:1,c:"Sc=22",u:true,ut:true,p:1};
I.u[10970] = {n:"Sudor de dragopavo",t:15,d:"Pero ¿cómo has hecho para conseguir eso? O mejor, ¿por qué lo has hecho?... Tú eres un poco rarito, ¿no?",ep:0,g:773,l:1,wd:false,fm:true,w:1,p:1};
I.u[10971] = {n:"Morral Lanac",t:81,d:"Equipado con este morral podrás hacer las mil y una canalladas y siempre con la sonrisa en los labios, pillín.",ep:0,g:25,l:20,wd:false,fm:true,w:10,c:"Sc=23",p:1};
I.u[10972] = {n:"Seguidor cuerbok",t:31,d:"Aunque parezca muy afectuoso, sospechas que esta ave se escapará volando en cuanto se acerque el peligro.",ep:0,g:25,l:1,wd:false,fm:true,w:0,m:true,c:"Sc=24",p:0};
I.u[10973] = {n:"Pócima de destino desconocido",t:12,d:"Una voz resuena en tu conciencia diciéndote que no te bebas el contenido de este frasco. En realidad, ¡es tu nariz! Esta mezcla huele peor que el sobaco de un bwork centenario.",ep:0,g:189,l:20,wd:false,fm:true,w:1,c:"Sc=25",u:true,p:10};
I.u[10974] = {n:"Hada artificial festiva",t:74,d:"¡¡¡Que siga la FIESTAAAAAAAAAAAAAA!!!",ep:0,g:32,l:1,wd:false,fm:true,w:1,c:"Sc=26",ut:true,p:1};
I.u[10975] = {n:"",t:6,d:"",ep:0,g:97,l:33,wd:false,fm:false,w:10,an:14,e:[12,6,1,1,40,60,false,false],c:"CS>50",s:157,p:3100};
I.u[10976] = {n:"",t:9,d:"",ep:0,g:185,l:33,wd:false,fm:true,w:10,s:157,p:3150};
I.u[10977] = {n:"",t:10,d:"",ep:0,g:170,l:30,wd:false,fm:true,w:10,s:157,p:2650};
I.u[10978] = {n:"",t:11,d:"",ep:0,g:153,l:32,wd:false,fm:true,w:10,s:157,p:2900};
I.u[10979] = {n:"Martillo de Hectopp",t:7,d:"A Hectopp le encantaba ir arrastrando este martillo al andar. Es cierto que era más vago que el sastre de Tarzán, pero lo hacía sobre todo para anunciar su llegada a los rivales.\nEsta arma está impregnada de la magia de Hectopp. Puede que logres encarnarlo al usarla.",ep:0,g:74,l:30,wd:false,fm:false,w:10,an:15,e:[5,4,1,1,50,50,false,false],c:"CA>50",s:158,p:2800};
I.u[10980] = {n:"",t:1,d:"",ep:0,g:159,l:32,wd:false,fm:true,w:10,s:158,p:2900};
I.u[10981] = {n:"",t:9,d:"",ep:0,g:186,l:32,wd:false,fm:true,w:10,s:158,p:2970};
I.u[10982] = {n:"",t:10,d:"",ep:0,g:171,l:32,wd:false,fm:true,w:10,s:158,p:2900};
I.u[10984] = {n:"Amuleto del YeCh\'Ti",t:1,d:"Al colgar de tu cuello sobre tu pecho imberbe podrás aparentar ser tan peludo como el YeCh\'Ti, lo que puede llegar a asustar a tus enemigos.",ep:0,g:162,l:66,wd:false,fm:false,w:10,an:0,p:11500};
I.u[10985] = {n:"Miaumiau de las nieves",t:18,d:"Este miaumiau ha conocido las más duras nieves del Mundo de los Doce. Nadie sabe cómo ha llegado a Amakna, pero los ancianos comentan que alguien lo trajo desde la Isla de Frigost, donde todo el año es desiembro, para luchar contra la proliferación de wabbits. Esta mascota devoradora de almas sólo come wabbits.",ep:0,g:62,l:1,wd:true,fm:true,w:1,c:"PZ=1",p:1};
I.u[10986] = {n:"Fantasma de miaumiau de las nieves",t:90,d:"Este miaumiau de las nieves aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o de abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:62,l:1,wd:true,fm:true,w:1,p:1};
I.u[10991] = {n:"Regalo: miaumiau de las nieves",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10992] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10993] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10994] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10995] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10996] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10997] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10998] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[10999] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11000] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11001] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11002] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11003] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11004] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11005] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11006] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11007] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11008] = {n:"Certificado de admisión en la petrera: miaumiau de las nieves",t:77,d:"Este certificado describe las características del miaumiau de las nieves que has dejado en la petrera.",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[11009] = {n:"Hormona de miaumiau de las nieves",t:48,d:"Esta hormona de crecimiento deshidratada se puede utilizar en la elaboración de una potente pócima que mejorará a tu mascota.",ep:0,g:262,l:1,wd:true,fm:true,w:1,p:10};
I.u[11010] = {n:"Pócima de mejora de miaumiau de las nieves",t:116,d:"Si utilizas esta potente pócima aumentarás las capacidades de tu mascota de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:60,l:1,wd:true,fm:true,w:1,c:"PO=10985",u:true,p:10};
I.u[11011] = {n:"Pekefux atigrado",t:18,d:"El pekefux atigrado está algo más loco que el pekefux comun, pero la mayor diferencia es que es mucho menos pelirrojo que éste, y ya sabes lo que dicen de los pelirrojos...\nEsta mascota se alimenta del alma de criaturas que viven en el Árbol Hakam.",ep:0,g:63,l:1,wd:true,fm:true,w:10,c:"PZ=1",p:1};
I.u[11012] = {n:"",t:18,d:"",ep:0,g:64,l:1,wd:true,fm:true,w:10,c:"PZ=1",p:1};
I.u[11013] = {n:"",t:18,d:"",ep:0,g:65,l:1,wd:true,fm:true,w:10,c:"PZ=1",p:1};
I.u[11014] = {n:"",t:18,d:"",ep:0,g:66,l:1,wd:true,fm:true,w:10,c:"PZ=1",p:1};
I.u[11016] = {n:"",t:90,d:"",ep:0,g:63,l:1,wd:false,fm:true,w:1,p:1};
I.u[11017] = {n:"",t:90,d:"",ep:0,g:64,l:1,wd:false,fm:true,w:1,p:1};
I.u[11018] = {n:"",t:90,d:"",ep:0,g:65,l:1,wd:false,fm:true,w:1,p:1};
I.u[11019] = {n:"",t:90,d:"",ep:0,g:66,l:1,wd:false,fm:true,w:1,p:1};
I.u[11021] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11022] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11023] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11024] = {n:"",t:89,d:"",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11026] = {n:"",t:77,d:"",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[11027] = {n:"",t:77,d:"",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[11028] = {n:"",t:77,d:"",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[11029] = {n:"",t:77,d:"",ep:0,g:24,l:1,wd:false,fm:true,w:1,p:100};
I.u[11031] = {n:"",t:48,d:"",ep:0,g:263,l:1,wd:true,fm:true,w:1,p:10};
I.u[11032] = {n:"",t:48,d:"",ep:0,g:264,l:1,wd:true,fm:true,w:1,p:10};
I.u[11033] = {n:"",t:48,d:"",ep:0,g:265,l:1,wd:true,fm:true,w:1,p:10};
I.u[11034] = {n:"",t:48,d:"",ep:0,g:266,l:1,wd:true,fm:true,w:1,p:10};
I.u[11036] = {n:"Pócima de mejora para pekefux atigrados",t:116,d:"Al utilizar esta potente pócima aumentarás las capacidades de tu pekefux atigrado de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:63,l:1,wd:true,fm:true,w:1,c:"PO=11011",u:true,p:10};
I.u[11037] = {n:"Pócima de mejora para wauwaus  atigrados",t:116,d:"Al utilizar esta potente pócima aumentarás las capacidades de tu wuawua atigrado de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:64,l:1,wd:true,fm:true,w:1,c:"PO=11012",u:true,p:10};
I.u[11038] = {n:"Pócima de mejora para kuakuás negros",t:116,d:"Al utilizar esta potente pócima aumentarás las capacidades de tu kuakuá negro de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:65,l:1,wd:true,fm:true,w:1,c:"PO=11013",u:true,p:10};
I.u[11039] = {n:"Pócima de mejora para murciegos pálidos",t:116,d:"Al utilizar esta potente pócima aumentarás las capacidades de tu murciego pálido de forma definitiva. Ojo, tu mascota sólo puede asimilar una dosis... si le das más, puede que eso provoque resultados muy decepcionantes.",ep:0,g:66,l:1,wd:true,fm:true,w:1,c:"PO=11014",u:true,p:10};
I.u[11041] = {n:"Espada Hondbaz",t:6,d:"Pesada, poco manejable, desafilada y fea. Manejar esta espada no te hará más fuerte ni más temible, sólo más ridículo. Al verla uno se pregunta cómo ha hecho Gúltar para ser tan temible manejando una espada tan mediocre.",ep:0,g:99,l:40,wd:false,fm:true,w:10,an:14,e:[6,4,1,1,40,40,false,false],s:159,p:4000};
I.u[11042] = {n:"Cordón Periñón",t:10,d:"Gúltar recibió este cinturón de manos de su padre, cuando tan sólo tenía 5 años. A pesar de su aspecto simple, este cinto te mantendrá el pantalón a la altura de la cadera. Además, puede servir de cuerda para tender la ropa o ¡hasta de comba!",ep:0,g:175,l:40,wd:false,fm:true,w:10,s:159,p:4300};
I.u[11043] = {n:"Gorro Kalipsis",t:16,d:"Este gorro va tan prieto que comprime el cráneo y provoca alucinaciones. Por suerte, Gúltar sólo lo llevaba de joven, y además de poco relleno, su cráneo era pequeño. Esto delata sus orígenes...",ep:0,g:265,l:41,wd:false,fm:true,w:10,s:159,p:4500};
I.u[11044] = {n:"Restos de la familia de Gúltar",t:24,d:"Huesos, polvo y alguna joya mortuoria, esto es todo lo que transportas.",ep:0,g:818,l:1,wd:false,fm:true,w:0,p:0};
I.u[11045] = {n:"Capa Stinencia",t:17,d:"Gúltar llevó esta capa hasta que conoció a las tres hermanas. Luego la olvidó en el fondo de un armario.",ep:0,g:179,l:43,wd:false,fm:true,w:10,s:159,p:5050};
I.u[11046] = {n:"Collar maldito de Cabotina",t:24,d:"Con lo potente que es el aura maléfica de este collar, te cuesta muchísimo no deshacerte de él.",ep:0,g:819,l:1,wd:false,fm:true,w:0,p:0};
I.u[11047] = {n:"De Rorc",t:32,d:"De Rorc se ha rendido, llévaselo preso a Letalina.",ep:0,g:29,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[11048] = {n:"Pistas para DarkVlad",t:24,d:"Un plano muy sencillo y una pócima de inteligencia. Con esto,  incluso Dark Vlad debería ser capaz de salir de su laberinto.",ep:0,g:820,l:1,wd:false,fm:true,w:0,p:0};
I.u[11049] = {n:"",t:16,d:"",ep:0,g:262,l:32,wd:false,fm:true,w:10,s:161,p:2900};
I.u[11050] = {n:"",t:17,d:"",ep:0,g:177,l:32,wd:false,fm:true,w:10,s:161,p:2850};
I.u[11051] = {n:"",t:1,d:"",ep:0,g:161,l:32,wd:false,fm:true,w:10,s:161,p:2925};
I.u[11052] = {n:"",t:11,d:"",ep:0,g:161,l:34,wd:false,fm:true,w:10,an:0,s:161,p:3205};
I.u[11055] = {n:"",t:16,d:"",ep:0,g:263,l:41,wd:false,fm:true,w:10,an:0,s:162,p:4553};
I.u[11056] = {n:"",t:17,d:"",ep:0,g:178,l:42,wd:false,fm:true,w:10,an:0,s:162,p:4875};
I.u[11057] = {n:"",t:10,d:"",ep:0,g:174,l:40,wd:false,fm:true,w:10,an:0,s:162,p:4305};
I.u[11058] = {n:"",t:9,d:"",ep:0,g:189,l:43,wd:false,fm:true,w:10,an:0,s:162,p:5100};
I.u[11059] = {n:"Regalo: Espada Hondbaz",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11060] = {n:"Regalo: Cordón Periñón",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11061] = {n:"Regalo: Gorro Kalipsis",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11062] = {n:"Regalo: Capa Stinencia",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11063] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11064] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11065] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11066] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11067] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11068] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11069] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11070] = {n:"Hata Mari",t:32,d:"Estaba presa de los bworks, ahora quiere que la escoltes hasta fuera de ese pueblo.",ep:0,g:30,l:1,wd:false,fm:true,w:0,m:true,p:0};
I.u[11071] = {n:"Extracto de los orígenes de Gúltar",t:25,d:"Manchadas, arrugadas, rasgadas... ¡estas hojas son casi ilegibles! Sin embargo, tras la espesa capa de roña logras adivinas unas pocas palabras. Estas páginas fueron sacadas de una obra olvidada que narraba los orígenes de Gúltar.",ep:0,g:9,l:1,wd:false,fm:true,w:1,u:true,p:0};
I.u[11072] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11073] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11074] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11075] = {n:"",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11076] = {n:"Regalo: Set Escarchado",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11077] = {n:"Martillo de Lonn",t:7,d:"A la hora de  noquear al adversario, Lonn Jehnon no siempre repite la misma cantinela. Basta con ver como su laúd es también su martillo...",ep:0,g:75,l:54,wd:false,fm:true,w:20,an:0,e:[6,5,1,1,42,50,false,false],c:"CA>20&CV>40",s:163,p:9700};
I.u[11078] = {n:"",t:17,d:"",ep:0,g:176,l:55,wd:false,fm:true,w:10,an:0,s:163,p:7900};
I.u[11079] = {n:"",t:16,d:"",ep:0,g:261,l:55,wd:false,fm:true,w:10,an:0,s:163,p:8050};
I.u[11080] = {n:"",t:11,d:"",ep:0,g:160,l:55,wd:false,fm:false,w:10,an:0,s:163,p:7925};
I.u[11082] = {n:"",t:11,d:"",ep:0,g:157,l:28,wd:false,fm:true,w:10,an:0,c:"Sc=11",p:2300};
I.u[11083] = {n:"",t:9,d:"",ep:0,g:187,l:31,wd:false,fm:true,w:10,an:0,c:"Sc=12",p:2666};
I.u[11084] = {n:"Sombrero de Gadjèt",t:16,d:"Gadjèt era uno de los manitas más creativos del Mundo de los Doce, pero por desgracia también uno de los más despistados. Se cuenta que un día hasta confundió entre su yunque y la cabeza de su mujer. “¡Una suerte que los yunques no griten!” dijo al respecto...",ep:0,g:0,l:49,wd:false,fm:true,w:10,an:0,s:165,p:6400};
I.u[11085] = {n:"Cinturón de Gadjèt",t:10,d:"Si te pones este cito del revés y lo aprietas lo bastante fuerte, puede que consigas activar el módulo integrado de retromagia. Nunca ha funcionado correctamente, pero siempre puedes intentar activarlo a ver que pasa... y luego venderle el cinturón a otro igual de inocente que tú.",ep:0,g:0,l:49,wd:false,fm:true,w:10,an:0,s:165,p:6358};
I.u[11086] = {n:"Capa de Gadjèt",t:17,d:"Gadjèt fabricó esta capa esperando poder volar con ella. Su objetivo final era escapar más fácilmente de los castigos cotidianos que le administraba su mujer.",ep:0,g:0,l:49,wd:false,fm:true,w:10,an:0,s:165,p:6350};
I.u[11087] = {n:"Anillo de Gadjèt",t:9,d:"Muchas generaciones de manitas han usado este anillo, que te protegerá las falanges de los golpes de martillo. Desgraciadamente, no se vende por lotes de cinco.",ep:0,g:0,l:49,wd:false,fm:true,w:10,an:0,s:165,p:6453};
I.u[11088] = {n:"Sombrero de Grilyan",t:16,d:"Grilyan era un gran mago, famoso por haber inventado las bolsitas de te impermeables... aunque luego olvidó como fabricarlas.",ep:0,g:0,l:49,wd:false,fm:true,w:10,s:164,p:6325};
I.u[11089] = {n:"Capa de Grilyan",t:17,d:"Esta capa debería ser capaz de protegerte el trasero de las mordeduras de las monstruoplantas.",ep:0,g:0,l:48,wd:false,fm:true,w:10,s:164,p:6250};
I.u[11090] = {n:"Anuncio de busca y captura",t:24,d:"“Se busca: Letalina Sigisbul” pone en la cabezera de este cartel.",ep:0,g:821,l:1,wd:false,fm:true,w:0,p:0};
I.u[11091] = {n:"Botas de Grilyan",t:11,d:"Según parece, el mago Grilyan caombió un anillo mágico por este par de botas. Si esto es cierto, fue una estafa porque estas botas  ni siquiera tienen forro interior.",ep:0,g:0,l:46,wd:false,fm:true,w:10,an:0,s:164,p:5600};
I.u[11092] = {n:"Amuleto de Grilyan",t:1,d:"Grilyan llevaba puesto este amuleto justo en el momento en que... en que... ¿y qué más da? Ahora Grilyan está muerto y su amuleto te pertenece.",ep:0,g:0,l:45,wd:false,fm:true,w:10,s:164,p:5450};
I.u[11093] = {n:"Regalo: Martillo de Lonn",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11094] = {n:"Regalo: Capa de Lonn",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11095] = {n:"Regalo: Sombrero de Lonn",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11096] = {n:"Regalo: Botas de Lonn",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11097] = {n:"Regalo: Pócima de cambio de nombre",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11098] = {n:"Regalo: Pócima de cambio de colores",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11099] = {n:"Regalo: Pócima de cambio de sexo",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11100] = {n:"Regalo: Extracto de los orígenes de Gúltar",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11102] = {n:"",t:35,d:"",ep:0,g:635,l:100,wd:false,fm:true,w:1,p:0};
I.u[11103] = {n:"",t:100,d:"",ep:0,g:57,l:1,wd:false,fm:true,w:50,u:true,p:100};
I.u[11104] = {n:"Kuakuá mejorado",t:18,d:"El kuakuá mejorado ahora supera al tofu, al jalató e incluso a los yopukas. ¡Nada es más estúpido que un kuakuá mejorado!",ep:0,g:8,l:1,wd:true,fm:false,w:10,c:"PZ=1",p:1};
I.u[11105] = {n:"Fantasma de kuakuá mejorado",t:90,d:"Este kuakuá aún no ha dejado el mundo de los vivos, te toca encontrar la forma de resucitarlo o decidir abandonarlo definitivamente como buen cobarde que eres.",ep:0,g:12,l:1,wd:true,fm:true,w:1,p:1};
I.u[11106] = {n:"",t:41,d:"",ep:0,g:403,l:100,wd:false,fm:true,w:1,p:100};
I.u[11107] = {n:"",t:38,d:"",ep:0,g:677,l:100,wd:false,fm:true,w:5,p:100};
I.u[11109] = {n:"",t:34,d:"",ep:0,g:552,l:100,wd:false,fm:true,w:1,p:100};
I.u[11111] = {n:"",t:100,d:"",ep:0,g:59,l:1,wd:false,fm:true,w:50,u:true,p:100};
I.u[11112] = {n:"",t:100,d:"",ep:0,g:58,l:1,wd:false,fm:true,w:250,u:true,p:100};
I.u[11113] = {n:"",t:100,d:"",ep:0,g:60,l:1,wd:false,fm:true,w:50,u:true,p:100};
I.u[11114] = {n:"",t:100,d:"",ep:0,g:34,l:1,wd:false,fm:true,w:250,u:true,p:100};
I.u[11115] = {n:"Pehkaíto d\'aperirel",t:30,d:"Parece que volvió la primavera. El olor de las flores, del campo verde... pero sobre todo la peste de ese úridnac que llevas a la espalda.",ep:0,g:1,l:1,wd:false,fm:false,w:0,m:true,p:0};
I.u[11116] = {n:"Úridnac",t:94,d:"A este pescado le gusta mucho la gente, así que se quedará pegado al primer bañista que se despiste \nSin embargo, tiene un ritmo biológico bastante particular: Se tira todo el año hibernando, salvo durante el mes de aperirel, cuando Siluate caluenta las dulces aguas en que propsera.",ep:0,g:19,l:1,wd:false,fm:false,w:1,c:"SG=3&POX11115",u:true,ut:true,p:0};
I.u[11117] = {n:"",t:57,d:"",ep:0,g:211,l:105,wd:false,fm:true,w:1,an:0,p:10};
I.u[11118] = {n:"",t:47,d:"",ep:0,g:660,l:105,wd:false,fm:true,w:1,an:0,p:10};
I.u[11119] = {n:"",t:106,d:"",ep:0,g:624,l:96,wd:false,fm:true,w:10,p:1};
I.u[11121] = {n:"",t:109,d:"",ep:0,g:590,l:112,wd:false,fm:true,w:10,p:1};
I.u[11122] = {n:"",t:47,d:"",ep:0,g:661,l:112,wd:false,fm:true,w:10,p:1};
I.u[11123] = {n:"",t:24,d:"",ep:0,g:822,l:1,wd:false,fm:true,w:0,p:1};
I.u[11124] = {n:"",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11125] = {n:"",t:24,d:"",ep:0,g:823,l:1,wd:false,fm:true,w:0,p:1};
I.u[11126] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11127] = {n:"",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11129] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11131] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11132] = {n:"",t:24,d:"",ep:0,g:824,l:1,wd:false,fm:true,w:0,p:1};
I.u[11134] = {n:"",t:94,d:"",ep:0,g:21,l:50,wd:false,fm:true,w:1,u:true,p:500};
I.u[11135] = {n:"",t:65,d:"",ep:0,g:752,l:118,wd:false,fm:true,w:10,p:1};
I.u[11136] = {n:"",t:57,d:"",ep:0,g:212,l:118,wd:false,fm:true,w:10,p:1};
I.u[11137] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11138] = {n:"",t:24,d:"",ep:0,g:828,l:1,wd:false,fm:true,w:0,p:1};
I.u[11139] = {n:"",t:24,d:"",ep:0,g:829,l:1,wd:false,fm:true,w:0,p:1};
I.u[11141] = {n:"",t:24,d:"",ep:0,g:831,l:1,wd:false,fm:true,w:0,p:1};
I.u[11142] = {n:"",t:24,d:"",ep:0,g:832,l:1,wd:false,fm:true,w:0,p:1};
I.u[11143] = {n:"",t:24,d:"",ep:0,g:833,l:1,wd:false,fm:true,w:0,p:1};
I.u[11145] = {n:"",t:24,d:"",ep:0,g:835,l:1,wd:false,fm:true,w:0,p:1};
I.u[11146] = {n:"",t:24,d:"",ep:0,g:836,l:1,wd:false,fm:true,w:0,p:1};
I.u[11147] = {n:"",t:24,d:"",ep:0,g:837,l:1,wd:false,fm:true,w:0,p:1};
I.u[11148] = {n:"",t:24,d:"",ep:0,g:838,l:1,wd:false,fm:true,w:0,p:1};
I.u[11149] = {n:"",t:24,d:"",ep:0,g:839,l:1,wd:false,fm:true,w:0,p:1};
I.u[11156] = {n:"",t:24,d:"",ep:0,g:841,l:1,wd:false,fm:true,w:0,p:1};
I.u[11157] = {n:"",t:24,d:"",ep:0,g:842,l:1,wd:false,fm:true,w:0,p:1};
I.u[11158] = {n:"",t:24,d:"",ep:0,g:843,l:1,wd:false,fm:true,w:0,p:1};
I.u[11159] = {n:"",t:24,d:"",ep:0,g:844,l:1,wd:false,fm:true,w:0,p:1};
I.u[11160] = {n:"",t:24,d:"",ep:0,g:845,l:1,wd:false,fm:true,w:0,p:1};
I.u[11161] = {n:"",t:24,d:"",ep:0,g:846,l:1,wd:false,fm:true,w:0,p:1};
I.u[11162] = {n:"",t:24,d:"",ep:0,g:847,l:1,wd:false,fm:true,w:0,p:1};
I.u[11163] = {n:"",t:24,d:"",ep:0,g:848,l:1,wd:false,fm:true,w:0,p:1};
I.u[11164] = {n:"",t:24,d:"",ep:0,g:849,l:1,wd:false,fm:true,w:0,p:1};
I.u[11165] = {n:"",t:24,d:"",ep:0,g:850,l:1,wd:false,fm:true,w:0,p:1};
I.u[11166] = {n:"",t:24,d:"",ep:0,g:851,l:1,wd:false,fm:true,w:0,p:1};
I.u[11167] = {n:"",t:24,d:"",ep:0,g:852,l:1,wd:false,fm:true,w:0,p:1};
I.u[11174] = {n:"Llave de la Mazmorra de los Jalamúts",t:84,d:"Con esta llave podrás entrar en el invernáculo donde se esconde el Jalamut real.",ep:0,g:0,l:1,wd:false,fm:true,w:1,p:1};
I.u[11175] = {n:"Llave de la Mazmorra de los Güinos",t:84,d:"Los güinos utilizan esta llave porque tiene la peculiaridad de flotar sobre el agua salada. Con ella podrás entrar en su mazmorra.",ep:0,g:255,l:1,wd:false,fm:true,w:1,p:1};
I.u[11182] = {n:"Peluquín del Jalamut Real",t:24,d:"Resulta obvio que, sin su peluquín, la autoridad del Jalamut Real se va a resentir.",ep:0,g:826,l:1,wd:false,fm:true,w:0,p:1};
I.u[11183] = {n:"",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11184] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11185] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11186] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11187] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11188] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11189] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11190] = {n:"Regalo: Amuleto del YeCh\'Ti",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11191] = {n:"Botas del mazmorreitor",t:11,d:"Tienen las suelas desgastadas, pero son muy cómodas. Estas botas han pisado el suelo de las mazmorras más escabrosas y la cabeza de las criaturas más tenebrosas.",ep:0,g:162,l:73,wd:true,fm:true,w:10,an:0,p:13700};
I.u[11192] = {n:"Regalo: Mazmorreitor",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. Atención, este regalo sólo puede abrirse en DOFUS 2.0.",ep:0,g:42,l:1,wd:false,fm:true,w:1,c:"Sc=997",u:true,p:1};
I.u[11193] = {n:"Tabla de álamo temblón",t:95,d:"Con esta plancha, los manitas pueden construir cosas de madera como, por ejemplo, un sarcófago de madera.",ep:0,g:23,l:100,wd:false,fm:true,w:10,p:10};
I.u[11194] = {n:"Harina de sucaritazz",t:52,d:"Esta harina tiene la particularidad de disolverse en la leleche, dándole así un peculiar sabor a chocolate. Los habitantes de una antigua isla desaparecida, adeptos de los postres con gelatina, preferían disolverla en agua.",ep:0,g:260,l:100,wd:false,fm:true,w:1,p:1};
I.u[11195] = {n:"El guesfguiado",t:30,d:"Tendrías que ir a que te curen, antes de que se agrave tu caso.",ep:0,g:2,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[11196] = {n:"Kama de hielo",t:24,d:"Como la falta de metal no les permitía acuñar más moneda, los frigsteños decidieron acuñar sobre hielo y usar estas monedas para el intercambio local. Esta moneda no tienen ningún valor al exterior de la isla.",ep:0,g:825,l:1,wd:false,fm:true,w:0,p:1};
I.u[11197] = {n:"La guinitis",t:30,d:"La campaña de vacunación contra esta enfermedad ya le ha costado al burgo de Frigost la módica suma de 2.000 millones de kamas y no ha dado ningún resultado concluyente. Cualquiera creería que a los frigosteños les gusta tirar el dinero por la ventana.",ep:0,g:7,l:1,wd:false,fm:true,w:0,m:true,p:1};
I.u[11198] = {n:"Vacuna contra el catago",t:24,d:"Esta vacuna te protege eficazmente contra el guesfguiado, pero sus efectos se disipan muy rápido así que tendrás que renovarla cada semana.",ep:0,g:31,l:1,wd:false,fm:true,w:0,p:1};
I.u[11199] = {n:"Grano de sucaritazz",t:58,d:"Este grano, frío al contacto, desprende un fuerte olor a cacao.",ep:0,g:0,l:100,wd:false,fm:true,w:1,p:1};
I.u[11200] = {n:"Regalo: Escudo HispáÑico",t:89,d:"Si agitas este regalo, te darás cuenta de que la caja no está vacía. Puede que por una vez los dioses no se hayan reído de ti. ",ep:0,g:42,l:1,wd:false,fm:true,w:1,u:true,p:1};
I.u[11201] = {n:"Muestra de sangre de jalamut",t:24,d:"Le has sacado esta muestra de sangre a un jalamut que tenía un guesfguiado.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11202] = {n:"Agua de mar isotónica",t:24,d:"Albert Pess necesita esta agua para su trabajo buscando una vacuna para el guesfguiado.",ep:0,g:764,l:1,wd:false,fm:true,w:0,p:1};
I.u[11203] = {n:"Altamisa",t:24,d:"Dadas sus propiedades, este hierbajo les resulta muy útil a los alquimistas, a los aniripsas y a los alquimistas aniripsas. Una planta análoga a esta también sirve para confeccionar un licor muy apreciado por los marineros, los anutrofs y los marineros anutrofs.",ep:0,g:103,l:1,wd:false,fm:true,w:0,p:1};
I.u[11204] = {n:"Muestra de sangre de La Bestia",t:24,d:"Te ha costado, pero al final has conseguido extraer esta muestra de sangre. Esperemos que resulte tan útil que valga la pena tanto esfuerzo.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11205] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11206] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11207] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11208] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11209] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11210] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11211] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11212] = {n:"",t:24,d:"",ep:0,g:50,l:1,wd:false,fm:true,w:0,p:1};
I.u[11213] = {n:"Garrapatas de jalamut",t:24,d:"Más resistentes que el calzoncillo de kriptonita del Capitán Chafer y más agresivas que un rebaño de rastreadores astrubienses, estas garrapatas son un auténtico calvario para su anfitrión.",ep:0,g:727,l:1,wd:false,fm:true,w:0,p:1};
I.u[11214] = {n:"Sangre de jalamut infectado",t:24,d:"Ésta es una muestra de sangre obtenida de un jalamut que estaba lleno de garrapatas.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11215] = {n:"Sangre de jalamut de guerra infectado",t:24,d:"Ésta es una muestra de sangre obtenida de un jalamut de guerra que estaba lleno de garrapatas.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11216] = {n:"Sangre de jalamut legendario infectado",t:24,d:"Ésta es una muestra de sangre obtenida de un jalamut legendario que estaba lleno de garrapatas.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11217] = {n:"Sangre de jalamutín infectado",t:24,d:"Ésta es una muestra de sangre obtenida de un jalamutín que estaba lleno de garrapatas.",ep:0,g:102,l:1,wd:false,fm:true,w:0,p:1};
I.u[11218] = {n:"Sobre para Otomai",t:24,d:"Wogew Lewmitanyo te ha encargado que le des este sobre a Otomai. En el hay varios documentos con información importante sobre las garrapatas que atacan a los jalamúts, y también a los wabbits.",ep:0,g:65,l:1,wd:false,fm:true,w:0,p:1};
I.u[11219] = {n:"Cola del Jalamut Real",t:65,d:"En verano, el Jalamút Real utiliza esta cola para espantar los moskitos. El resto del año no le sirve para nada, así que no es de extrañar que a veces se olvide de que la tiene.",ep:0,g:755,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11221] = {n:"Lana del Jalamut Real",t:57,d:"Nadie sabe exactamente cuando llegaron los jalamúts a Frigost. Lo que sí se sabe es que ya llevan mucho tiempo allá, porque aún se puede encontrar ropa interior hecha con lana de jalamut y transmitida de padres a hijos durante varias generaciones de frigosteños.",ep:0,g:213,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11222] = {n:"Pico de pekegüino",t:47,d:"Cuando no está firmemente pegado a la cabeza del pekegüino, este pico suele estar firmemente clavado en tus nalgas",ep:0,g:662,l:115,wd:false,fm:true,w:10,an:0,p:10};
I.u[11223] = {n:"Pluma de pekegüino",t:53,d:"Antaño, los pekagüinos sólo venían a la Isla de Frigost durante unos días de invierno. Ahora que la isla está helada han decidido quedarse. ¡Una ocasión perfecta para desemplumarlos todo el año!",ep:0,g:646,l:115,wd:false,fm:true,w:10,an:0,p:10};
I.u[11224] = {n:"Ala de barrigüino",t:104,d:"Ni siquiera los frigosteños saben para qué le sirven al barrigüino unas alas tan ridículamente pequeñas... evidentemente, no para volar, ¡ni siquiera para despegar!",ep:0,g:216,l:120,wd:false,fm:true,w:10,an:0,p:10};
I.u[11225] = {n:"Piel de barrigüino",t:59,d:"Es grasienta, parece que no la han lavado nunca y brilla. No, no se trata de tu peluquín, sino de la piel de un barrigüino.",ep:0,g:49,l:120,wd:false,fm:true,w:10,an:0,p:10};
I.u[11226] = {n:"Aceite de mamagüina",t:60,d:"Este aceite se ha extraído del cadáver de una mamagüina. Haces todo lo posible por no recordar lo que tuviste que hacer para obtenerlo.",ep:0,g:72,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11227] = {n:"Pelusa de mamagüina",t:54,d:"A todos los frigosteños les gusta rellenar su ropa interior con bolas de esta pelusa. Algunos dice que se para pasar menos frio... sólo los yopukas se lo siguen creyendo.",ep:0,g:675,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11228] = {n:"Espina gigante de chamángüino",t:47,d:"En Frigost hay muchas preguntas que no tiene respuesta, pero lo que es aún más inquietante, ¡también hay muchas respuestas que no tienen pregunta! ¿Resultado? Nunca sabrás de dónde sacó esta espina el chamángüino.",ep:0,g:663,l:130,wd:false,fm:true,w:10,an:0,p:10};
I.u[11229] = {n:"Pelo de barba de chamángüino",t:54,d:"La barba del chamángüino apesta a pescado y a espuma de acerdar. Los frigosteños aprecian muy particularmente esta deliciosa mezcla, pues sirve como repelente de jalamuts, y también de amigos molestos.",ep:0,g:674,l:130,wd:false,fm:true,w:10,an:0,p:10};
I.u[11230] = {n:"Cola de pingüindos",t:65,d:"No te fíes de su pequeño tamaño, esta cola sabe llegar a su destino sin perderse en el camino.",ep:0,g:753,l:135,wd:false,fm:true,w:10,an:0,p:10};
I.u[11231] = {n:"Oreja de pingüindos",t:106,d:"Como suelen estar ocultas por un pez medio descompuesto, las orejas del pingüindos sólo oyen una cosa: la llamada de compañeras disponibles durante el periodo de reproducción. Por consiguiente puedes reírte del pingüindos a su cara sin correr ningún riesgo, a no ser que te parezcas a una posible compañera...",ep:0,g:625,l:135,wd:false,fm:true,w:10,an:0,p:10};
I.u[11232] = {n:"Pluma del Morsagüino Real",t:53,d:"Los frigosteños respetan mucho al Morsagüino Real, ya que lo ven como un bicho que tiene un título importante, así que es la ocasión de matar algo importante.",ep:0,g:647,l:145,wd:false,fm:true,w:10,an:0,p:10};
I.u[11233] = {n:"Huevo del Morsagüino Real",t:105,d:"No hace falta que finjas estar sorprendido, este enorme huevo ha tenido que salir de algún sitio...",ep:0,g:643,l:135,wd:false,fm:true,w:10,an:0,p:10};
I.u[11234] = {n:"Reltux Richards",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:false,w:0,an:0,m:true,p:1};
I.u[11235] = {n:"Ally Storm",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:false,w:0,an:0,m:true,p:1};
I.u[11236] = {n:"ViKonny Storm",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:false,w:0,an:0,m:true,p:1};
I.u[11237] = {n:"Bern Grim",t:32,d:"",ep:0,g:0,l:1,wd:false,fm:false,w:0,an:0,m:true,p:1};
I.u[11238] = {n:"Cola de ardilla de las nieves",t:65,d:"",ep:0,g:754,l:115,wd:false,fm:true,w:10,an:0,p:10};
I.u[11239] = {n:"Bellota de ardilla de las nieves",t:58,d:"",ep:0,g:68,l:115,wd:false,fm:true,w:10,an:0,p:10};
I.u[11240] = {n:"Diente de smielodón",t:47,d:"",ep:0,g:664,l:120,wd:false,fm:true,w:10,an:0,p:10};
I.u[11241] = {n:"Pelo de smielodón",t:54,d:"",ep:0,g:676,l:120,wd:false,fm:true,w:10,an:0,p:10};
I.u[11242] = {n:"Colmillo de jabajocero",t:47,d:"",ep:0,g:665,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11243] = {n:"Cuero de jabajocero",t:56,d:"",ep:0,g:16,l:125,wd:false,fm:true,w:10,an:0,p:10};
I.u[11244] = {n:"",t:24,d:"",ep:0,g:176,l:1,wd:false,fm:true,w:0,p:1};
I.u[11245] = {n:"null",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11246] = {n:"Ojo torvo de frigóquero",t:109,d:"Antes de marcharse hacia el santuario de los frigóqueros muertos en combate, el que acabas de matar te ha lanzado una mirada capaz de helarle la sangre al más bravo. ¡Como si no hiciera ya bastante frío en Frigost!",ep:0,g:591,l:130,wd:false,fm:true,w:10,an:0,p:10};
I.u[11247] = {n:"Oreja de frigóquero agujereada",t:106,d:"Las orejas de frigóquero estás llenas de agujeros. ¿Será por su gusto por el piercing? ¿o será porque pueden oír las canciones de Badiz Mustabante desde Frigost?",ep:0,g:626,l:130,wd:false,fm:true,w:10,an:0,p:10};
I.u[11248] = {n:"Oreja de kaniglú",t:106,d:"Todo el mundo se pregunta para qué puede servir una oreja de kaniglú... Si quieres te cortamos una e intentamos coserte esta en su lugar, a ver si descubrimos un uso nuevo.",ep:0,g:627,l:135,wd:false,fm:true,w:10,an:0,p:10};
I.u[11249] = {n:"Tejido de kaniglú",t:55,d:"Este tejido te recuerda una canción infantil que cantan en las escuelas de Frigost: “Un kaniglú-ú se balanceaba sobre la tela de una araaaa-akna”... Desgraciadamente, no recuerdas como sigue.",ep:0,g:730,l:135,wd:false,fm:true,w:10,an:0,p:10};
I.u[11250] = {n:"Pelo de miaumiaumialvaje",t:54,d:"Cuando aún seguían vivos, los rivales políticos del alcalde del Burgo revelaban a quien quisiera oírles que éste usaba lencería de pelo de miaumiaumialvaje por ropa interior.",ep:0,g:677,l:85,wd:false,fm:true,w:10,an:0,p:10};
I.u[11251] = {n:"Esternón de miaumiaumialvaje",t:47,d:"Este esternón te recuerda una canción infantil que cantan en las escuelas de Frigost: “Estaba el miamiauuuuu-mialvaaaje sentadito en suuuuu tejado maramiaumiau ¡miau! ¡miau!”... Desgraciadamente, no recuerdas como sigue.",ep:0,g:666,l:85,wd:false,fm:true,w:10,an:0,p:10};
I.u[11252] = {n:"Pata de rata kekomepoko",t:103,d:"Los niños de Frigost tienen un juego al que llaman “Cazador cazado”. Para jugar a este juego hay que cortarle una pata a una rata kekomepoko, luego se usa esta pata para dejar un rastro en la nieve y atraer un miaumiau de la nieves. Le tienden una emboscada al miaumiau y, cuando consiguen atraparlo, lo esquilan y lo transforman en pantuflas. Los niños son maravillosos.",ep:0,g:36,l:95,wd:false,fm:true,w:10,an:0,p:10};
I.u[11253] = {n:"Piel de rata kekomepoko",t:55,d:"Antes de la glaciación de Frigost, se cazaba a las ratas kekomepokos por su piel, que luego se exportaba al continente amakneano y se vendía bajo la apelación de “piel de kitsu exótica”.",ep:0,g:731,l:95,wd:false,fm:true,w:10,an:0,p:10};
I.u[11254] = {n:"Pinza de cangrabino",t:47,d:"En Frigost se caza al cangrabino por dos motivos: su mal humor y su costumbre de gastarle bromas a los pescadores cortándoles las redes. Para vengarse, los pescadores les gastan bromas a los cangrabinos cotándoles a su vez las pinzas.",ep:0,g:668,l:65,wd:false,fm:true,w:10,an:0,p:10};
I.u[11255] = {n:"Ojo de cangrabino",t:109,d:"Este ojo contiene un humor vítreo utilizado en muchas recetas tradicionales de la cocina frigóstea en sustitución del vinagre. Pero antes de usarlo así, hay que dejar fermentar el ojo durante bastante tiempo.",ep:0,g:592,l:65,wd:false,fm:true,w:10,an:0,p:10};
I.u[11256] = {n:"Pico de heladíkano",t:47,d:"El heladíkano es una criatura bastante estúpida y maleducada. Va dejando guano por todas partes (basta con ver el puerto de Frigost) y además tiende a robarle el pescado a lo pescadores, pero si se le entrena bien puede esconder en su pico las joyas y carteras de los turistas despistados.",ep:0,g:667,l:75,wd:false,fm:true,w:10,an:0,p:10};
I.u[11257] = {n:"Pluma de heladíkano",t:53,d:"Los niños de Frigost utilizan estas plumas para escribir en sus cuadernos de clase. Por eso las mamás heladíkanas explican a su hijos que siempre hay que acelerar al pasar por delante de una escuela.",ep:0,g:648,l:75,wd:false,fm:true,w:10,an:0,p:10};
I.u[11258] = {n:"",t:24,d:"",ep:0,g:26,l:1,wd:false,fm:true,w:0,p:1};
I.u[11259] = {n:"",t:24,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:0,p:1};
I.u[11260] = {n:"",t:24,d:"",ep:0,g:500,l:1,wd:false,fm:true,w:0,p:1};
I.u[11261] = {n:"",t:24,d:"",ep:0,g:41,l:1,wd:false,fm:true,w:0,p:1};
I.u[11262] = {n:"",t:24,d:"",ep:0,g:27,l:1,wd:false,fm:true,w:0,p:1};
I.u[11263] = {n:"",t:74,d:"",ep:0,g:0,l:1,wd:false,fm:true,w:1,ut:true,p:1};
